import React, { createContext, useContext, useEffect, useState } from "react";

type Language = "en" | "ar";

interface LanguageContextValue {
  lang: Language;
  dir: "ltr" | "rtl";
  t: (key: string) => string;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // General
    "lang.en": "English",
    "lang.ar": "العربية",
    "nav.home": "Home",
    "nav.clinics": "Clinics",
    "nav.labs": "Labs",
    "nav.radiology": "Radiology",
    "nav.backToHome": "Back to Home",
    "auth.signIn": "Sign In",
    "auth.getStarted": "Get Started",
    "auth.login": "Log in",
    "auth.loginDescription": "Sign in to your patient account",
    "auth.register": "Register",
    "auth.registerDescription": "Create a patient account",
    "auth.logout": "Log out",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm password",
    "auth.name": "Full name",
    "auth.age": "Age",
    "auth.phone": "Phone",
    "auth.address": "Address",
    "auth.gender": "Gender",
    "auth.genderMale": "Male",
    "auth.genderFemale": "Female",
    "auth.bloodGroup": "Blood group",
    "auth.whatsapp": "WhatsApp",
    "auth.optional": "optional",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.signingIn": "Signing in…",
    "auth.creatingAccount": "Creating account…",
    "auth.passwordMismatch": "Passwords do not match",
    "auth.passwordMin": "Password must be at least 6 characters",
    "auth.dashboardLogin": "Dashboard sign in",
    "auth.dashboardLoginDescription": "Sign in to clinic, admin, lab, or radiology dashboard via the backend.",
    "auth.dashboardLoginNote": "Sign in below to access your dashboard.",
    "auth.edit": "Edit",
    "auth.backToDashboardLogin": "Back to dashboard login",
    "auth.clinicLogin": "Clinic sign in",
    "auth.clinicLoginDesc": "Sign in to your clinic dashboard",
    "auth.labLogin": "Lab sign in",
    "auth.labLoginDesc": "Sign in to your medical lab dashboard",
    "auth.radiologyLogin": "Radiology sign in",
    "auth.radiologyLoginDesc": "Sign in to your radiology center dashboard",
    "auth.clinicRegister": "Register clinic",
    "auth.clinicRegisterDesc": "Submit your clinic for approval",
    "auth.labRegister": "Register medical lab",
    "auth.labRegisterDesc": "Submit your lab for approval",
    "auth.radiologyRegister": "Register radiology center",
    "auth.radiologyRegisterDesc": "Submit your radiology center for approval",
    "auth.clinicName": "Clinic name",
    "auth.labName": "Medical lab name",
    "auth.radiologyName": "Radiology center name",
    "auth.startDate": "Start date",
    "auth.specialty": "Specialty",
    "auth.clinicEmail": "Clinic email",
    "auth.labEmail": "Lab email",
    "auth.radiologyEmail": "Radiology center email",
    "auth.select": "Select",

    // Public
    "brand.name": "MediCare",
    "public.footer.platform": "Platform",
    "public.footer.dashboards": "Dashboards",
    "public.footer.description":
      "Your trusted platform for finding clinics, doctors, and booking appointments.",
    "public.footer.clinic": "Clinic",
    "public.footer.admin": "Admin",
    "public.footer.copyright": "All rights reserved.",

    // Dashboards titles
    "clinic.title": "Clinic Dashboard",
    "admin.title": "Admin Dashboard",
    "lab.title": "Lab Dashboard",
    "radiology.title": "Radiology Dashboard",
    "patient.title": "Patient Portal",

    // Clinic sidebar
    "clinic.menu.dashboard": "Dashboard",
    "clinic.menu.reservations": "Reservations",
    "clinic.menu.reservations_management": "Reservations Management",
	"clinic.menu.clinic_management": "Clinic Management",
	"clinic.menu.users_management": "Users Management",
	"clinic.menu.users": "Users",
	"clinic.menu.roles": "Roles & Permissions",
	"clinic.menu.reviews": "Reviews",
	"clinic.menu.announcements": "Announcements",
	"clinic.menu.notifications": "Notifications",
	"clinic.menu.services": "Services",
	"clinic.menu.inventory": "Inventory",
	"clinic.menu.modules": "Modules",
	"clinic.menu.financial": "Financial",
	"clinic.menu.trash": "Trash",
    "clinic.menu.today": "Today",
    "clinic.menu.numbers": "Reservation Numbers",
    "clinic.menu.slots": "Reservation Slots",
    "clinic.menu.doctors": "Doctors",
    "clinic.menu.patients": "Patients",
    "clinic.menu.chat": "Chat",

    // Clinic dashboard
    "clinic.dashboard.Dashboard": "Dashboard",
    "clinic.dashboard.AddReservation": "Add Reservation",
    "clinic.dashboard.TodayReservations": "Today Reservations",
    "clinic.dashboard.TotalPatients": "Total Patients",
    "clinic.dashboard.RevenueMonth": "Revenue Month",
    "clinic.dashboard.AvgWaitTime": "Avg. Wait Time",
    "clinic.dashboard.YouMustBeSignedInToViewTheClinicDashboard": "You must be signed in to view the clinic dashboard.",
    "clinic.dashboard.SignIn": "Sign In",
    "clinic.dashboard.ViewAll": "View All",
    "clinic.dashboard.NoReservationsToday": "No reservations today.",

    // Admin sidebar
    "admin.menu.dashboard": "Dashboard",
    "admin.menu.clinics": "Clinics",
    "admin.menu.labs": "Medical Labs",
    "admin.menu.radiology": "Radiology Centers",
    "admin.menu.specialties": "Specialties",
    "admin.menu.locations": "Locations",
    "admin.menu.users": "Users & Roles",
    "admin.menu.reviews": "Reviews",
    "admin.menu.announcements": "Announcements",
    "admin.menu.financial": "Financial",

    // Lab sidebar
    "lab.menu.dashboard": "Dashboard",
    "lab.menu.users_management": "Users Management",
    "lab.menu.medical_analyses_management": "Medical Analyses Management",
    "lab.menu.chat": "Chat",
    "lab.menu.patients": "Patients",
    "lab.menu.users": "Users",
    "lab.menu.service_categories": "Service Categories",
    "lab.menu.services": "Services",
    "lab.menu.medical_analyses": "Medical Analyses",
    "lab.menu.financial": "Financial",
    "lab.menu.today_medical_analyses": "Today's Analyses",
    "lab.menu.roles": "Roles",
    "lab.menu.notifications": "Notifications",

    // Lab patients
    "lab.patients.title": "Patients",
    "lab.patients.assign_existing": "Assign Existing (Code / QR)",
    "lab.patients.add": "Add Patient",
    "lab.patients.patient_code": "Patient Code",
    "lab.patients.name": "Name",
    "lab.patients.phone": "Phone",
    "lab.patients.age": "Age",
    "lab.patients.gender": "Gender",
    "lab.patients.blood": "Blood",
    "lab.patients.status": "Status",
    "lab.patients.actions": "Actions",

    // Lab users
    "lab.users.title": "Users",
    "lab.users.description": "Users assigned to this laboratory organization",
    "lab.users.search": "Search by name, email, role...",
    "lab.users.name": "Name",
    "lab.users.email": "Email",
    "lab.users.permissions": "Permissions",
    "lab.users.status": "Status",
    "lab.users.actions": "Actions",
	"lab.users.loading": "Loading...",
	"lab.users.job": "Job Title",
	"lab.users.phone": "Phone",
	"lab.users.role": "Role",
	"lab.users.select_role": "Select Role",
	"lab.users.additional_permissions": "Additional Permissions",
	"lab.users.permission": "Permission",
	"lab.users.delete_user": "Delete User",
	"lab.users.delete_user_description": "This will deactivate the user account.",
	"lab.users.deleting": "Deleting...",
	"lab.users.delete": "Delete",
	"lab.users.cancel": "Cancel",
	"lab.users.saving": "Saving...",
	"lab.users.save": "Save",
	"lab.users.close": "Close",
	"lab.users.add": "Add User",
	"lab.users.edit": "Edit User",
	"lab.users.show": "Show",
	"lab.users.total": "Total",
	"lab.users.no_users_found": "No users found.",
	"lab.users.page": "Page",
	"lab.users.of": "of",
	"lab.users.details": "User Details",
	"lab.users.activate": "Activate",
	"lab.users.activate_user": "Activate User",
	"lab.users.activate_user_description": "This will activate the user account.",
	"lab.users.leave_empty_to_keep_current_password": "Leave empty to keep current password",

// Lab service categories
"lab.service_categories.title": "Service Categories",
"lab.service_categories.description": "Service categories available in the laboratory",
"lab.service_categories.search": "Search by category name...",
"lab.service_categories.category": "Category",
"lab.service_categories.services": "Services",
"lab.service_categories.status": "Status",
"lab.service_categories.actions": "Actions",
"lab.service_categories.loading": "Loading...",
"lab.service_categories.add": "Add Category",
"lab.service_categories.created": "Created",
"lab.service_categories.edit": "Edit Category",
"lab.service_categories.category_name": "Category Name",
"lab.service_categories.close": "Close",
"lab.service_categories.saving": "Saving...",
"lab.service_categories.save": "Save",
"lab.service_categories.delete_confirmation": "This action cannot be undone.",
"lab.service_categories.deleting": "Deleting...",
"lab.service_categories.delete": "Delete",
"lab.service_categories.active": "Active",
"lab.service_categories.inactive": "Inactive",
"lab.service_categories.details": "Category Details",
"lab.service_categories.loading_categories": "Loading categories...",
"lab.service_categories.category_updated": "Category updated",
"lab.service_categories.category_deleted": "Category deleted",
"lab.service_categories.category_created": "Category created",
"lab.service_categories.failed_to_update_category": "Failed to update category",
"lab.service_categories.failed_to_delete_category": "Failed to delete category",
"lab.service_categories.category_name_required": "Category name is required",

// Lab services
"lab.services.title": "Services",
"lab.services.description": "Services available in the laboratory",
"lab.services.search": "Search by name, category, unit...",
"lab.services.category": "Category",
"lab.services.all_categories": "All Categories",
"lab.services.name": "Name",
"lab.services.price": "Price",
"lab.services.unit": "Unit",
"lab.services.normal_range": "Normal Range",
"lab.services.notes": "Notes",
"lab.services.close": "Close",
"lab.services.saving": "Saving...",
"lab.services.save": "Save",
"lab.services.delete_confirmation": "This action cannot be undone.",
"lab.services.deleting": "Deleting...",
"lab.services.delete": "Delete",
"lab.services.cancel": "Cancel",
"lab.services.loading_services": "Loading services...",
"lab.services.failed_to_load_services": "Failed to load services",
"lab.services.show": "Show",
"lab.services.edit": "Edit",
"lab.services.add": "Add Service",
"lab.services.details": "Service Details",
"lab.services.actions": "Actions",
"lab.services.select_category": "Select Category",
"lab.services.page": "Page",
"lab.services.of": "of",
"lab.services.total": "Total",
"lab.services.active": "Active",
"lab.services.inactive": "Inactive",
"lab.services.delete_confirmation_description": "This action cannot be undone.",

// Lab medical analyses
"lab.medical_analyses.title": "Medical Analyses",
"lab.medical_analyses.description": "Medical analyses available in the laboratory",
"lab.medical_analyses.no_analyses_found": "No analyses found.",
"lab.medical_analyses.search": "Search by name, category, unit...",
"lab.medical_analyses.category": "Category",
"lab.medical_analyses.all_categories": "All Categories",
"lab.medical_analyses.name": "Name",
"lab.medical_analyses.price": "Price",
"lab.medical_analyses.unit": "Unit",
"lab.medical_analyses.normal_range": "Normal Range",
"lab.medical_analyses.notes": "Notes",
"lab.medical_analyses.close": "Close",
"lab.medical_analyses.saving": "Saving...",
"lab.medical_analyses.save": "Save",
"lab.medical_analyses.delete_confirmation": "This action cannot be undone.",
"lab.medical_analyses.deleting": "Deleting...",
"lab.medical_analyses.delete": "Delete",
"lab.medical_analyses.cancel": "Cancel",
"lab.medical_analyses.loading_analyses": "Loading analyses...",
"lab.medical_analyses.failed_to_load_analyses": "Failed to load analyses",
"lab.medical_analyses.show": "Show",
"lab.medical_analyses.edit": "Edit",
"lab.medical_analyses.add": "Add Analysis",
"lab.medical_analyses.details": "Analysis Details",
"lab.medical_analyses.actions": "Actions",
"lab.medical_analyses.select_patient": "Select Patient",
"lab.medical_analyses.date": "Date",
"lab.medical_analyses.payment": "Payment",
"lab.medical_analyses.not_paid": "Not Paid",
"lab.medical_analyses.paid": "Paid",
"lab.medical_analyses.select_payment": "Select Payment",
"lab.medical_analyses.doctor_name": "Doctor Name",
"lab.medical_analyses.reservation_id_optional": "Reservation ID (optional)",
"lab.medical_analyses.report": "Report",
"lab.medical_analyses.services_values_and_media": "Services, Values, and Media",
"lab.medical_analyses.add_service": "Add Service",
"lab.medical_analyses.remove": "Remove",
"lab.medical_analyses.view_file": "View file",
"lab.medical_analyses.no_services_selected": "No services selected.",
"lab.medical_analyses.service": "Service",
"lab.medical_analyses.value": "Value",
"lab.medical_analyses.media": "Media",
"lab.medical_analyses.cost": "Cost",
"lab.medical_analyses.select_service": "Select Service",
"lab.medical_analyses.delete_analysis": "Delete Analysis?",
"lab.medical_analyses.delete_analysis_description": "This action cannot be undone.",
"lab.medical_analyses.filter_doctor": "Filter by doctor name",
"lab.medical_analyses.clear_filters": "Clear Filters",
"lab.medical_analyses.all_payments": "All Payments",
"lab.medical_analyses.today_title": "Today's Medical Analyses",
"lab.medical_analyses.today_description": "Medical analyses created for today",
"lab.medical_analyses.services": "services",
"lab.medical_analyses.view_file_description": "View file",


"lab.financial.title":"Lab Financial",
"lab.financial.description":"Revenue, due amounts, and payment trends for this laboratory.",

// Radiology sidebar
    "radiology.menu.dashboard": "Dashboard",
    "radiology.menu.reservations": "Reservations",
    "radiology.menu.rays": "Rays",
    "radiology.menu.users": "Users",
    "radiology.menu.patients": "Patients",
    "radiology.menu.roles": "Roles",
    "radiology.menu.financial": "Financial",
    "radiology.menu.notifications": "Notifications",

    // Patient sidebar
    "patient.menu.appointments": "Appointments",
    "patient.menu.profile": "Profile",
    "patient.menu.prescriptions": "Prescriptions",
    "patient.menu.analyses": "Medical Analyses",
    "patient.menu.rays": "Rays",
    "patient.menu.chronic": "Chronic Diseases",
    "patient.menu.glasses": "Glasses Distance",
    "patient.menu.reviews": "Reviews",
    "patient.menu.chat": "Chat",

	// Shared chat
	"shared.chat.title": "Chat",
	"shared.chat.description": "Real-time organization chat with users and assigned patients",
	"shared.chat.search": "Search conversations...",
	"shared.chat.no_conversations": "No conversations yet.",
	"shared.chat.patients": "Patients",
	"shared.chat.users": "Users",
	"shared.chat.message": "Message",
	"shared.chat.type_message": "Type your message...",
	"shared.chat.select_or_start_conversation": "Select or start a conversation.",
  },
  ar: {
    // General
    "lang.en": "English",
    "lang.ar": "العربية",
    "nav.home": "الرئيسية",
    "nav.clinics": "العيادات",
    "nav.labs": "المعامل",
    "nav.radiology": "الأشعة",
    "nav.backToHome": "العودة للرئيسية",
    "auth.signIn": "تسجيل الدخول",
    "auth.getStarted": "ابدأ الآن",
    "auth.login": "تسجيل الدخول",
    "auth.loginDescription": "سجّل الدخول إلى حساب المريض",
    "auth.register": "إنشاء حساب",
    "auth.registerDescription": "إنشاء حساب مريض",
    "auth.logout": "تسجيل الخروج",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.confirmPassword": "تأكيد كلمة المرور",
    "auth.name": "الاسم الكامل",
    "auth.age": "العمر",
    "auth.phone": "الهاتف",
    "auth.address": "العنوان",
    "auth.gender": "الجنس",
    "auth.genderMale": "ذكر",
    "auth.genderFemale": "أنثى",
    "auth.bloodGroup": "فصيلة الدم",
    "auth.whatsapp": "واتساب",
    "auth.optional": "اختياري",
    "auth.noAccount": "ليس لديك حساب؟",
    "auth.hasAccount": "لديك حساب بالفعل؟",
    "auth.signingIn": "جاري تسجيل الدخول…",
    "auth.creatingAccount": "جاري إنشاء الحساب…",
    "auth.passwordMismatch": "كلمتا المرور غير متطابقتين",
    "auth.passwordMin": "كلمة المرور 6 أحرف على الأقل",
    "auth.dashboardLogin": "تسجيل دخول لوحة التحكم",
    "auth.dashboardLoginDescription": "سجّل الدخول إلى لوحة العيادة أو الإدارة أو المعمل أو الأشعة عبر الخادم.",
    "auth.dashboardLoginNote": "سجّل الدخول أدناه للوصول إلى لوحة التحكم.",
    "auth.edit": "تعديل",
    "auth.backToDashboardLogin": "العودة لتسجيل دخول لوحة التحكم",
    "auth.clinicLogin": "تسجيل دخول العيادة",
    "auth.clinicLoginDesc": "سجّل الدخول إلى لوحة العيادة",
    "auth.labLogin": "تسجيل دخول المعمل",
    "auth.labLoginDesc": "سجّل الدخول إلى لوحة المعمل الطبي",
    "auth.radiologyLogin": "تسجيل دخول الأشعة",
    "auth.radiologyLoginDesc": "سجّل الدخول إلى لوحة مركز الأشعة",
    "auth.clinicRegister": "تسجيل عيادة",
    "auth.clinicRegisterDesc": "أرسل بيانات العيادة للمراجعة",
    "auth.labRegister": "تسجيل معمل طبي",
    "auth.labRegisterDesc": "أرسل بيانات المعمل للمراجعة",
    "auth.radiologyRegister": "تسجيل مركز أشعة",
    "auth.radiologyRegisterDesc": "أرسل بيانات مركز الأشعة للمراجعة",
    "auth.clinicName": "اسم العيادة",
    "auth.labName": "اسم المعمل الطبي",
    "auth.radiologyName": "اسم مركز الأشعة",
    "auth.startDate": "تاريخ البدء",
    "auth.specialty": "التخصص",
    "auth.clinicEmail": "بريد العيادة",
    "auth.labEmail": "بريد المعمل",
    "auth.radiologyEmail": "بريد مركز الأشعة",
    "auth.select": "اختر",

    // Public
    "brand.name": "ميدي كير",
    "public.footer.platform": "المنصة",
    "public.footer.dashboards": "لوحات التحكم",
    "public.footer.description":
      "منصتك الموثوقة للبحث عن العيادات والأطباء وحجز المواعيد.",
    "public.footer.clinic": "لوحة العيادة",
    "public.footer.admin": "لوحة الإدارة",
    "public.footer.copyright": "جميع الحقوق محفوظة.",

    // Dashboards titles
    "clinic.title": "لوحة العيادة",
    "admin.title": "لوحة الإدارة",
    "lab.title": "لوحة المعمل",
    "radiology.title": "لوحة الأشعة",
    "patient.title": "بوابة المريض",

    // Clinic sidebar
    "clinic.menu.dashboard": "الرئيسية",
    "clinic.menu.reservations": "الحجوزات",
     "clinic.menu.reservations_management": "أدارة الحجوزات",
    "clinic.menu.users_management": "إدارة المستخدمين",
    "clinic.menu.users": "المستخدمين",
    "clinic.menu.roles": "الصلاحيات والأدوار",
    "clinic.menu.clinic_management": "إدارة العيادة",
    "clinic.menu.services": "الخدمات",
    "clinic.menu.inventory": "المخزون",
    "clinic.menu.announcements": "الإعلانات",
    "clinic.menu.reviews": "التقييمات",
    "clinic.menu.today": "حجوزات اليوم",
    "clinic.menu.numbers": "أرقام الحجز",
    "clinic.menu.slots": "مواعيد الحجز",
    "clinic.menu.doctors": "الأطباء",
    "clinic.menu.patients": "المرضى",
    "clinic.menu.chat": "المحادثات",
    "clinic.menu.notifications": "الإشعارات",
    "clinic.menu.modules": "الوحدات",
    "clinic.menu.financial": "الحسابات",
    "clinic.menu.trash": "سلة المحذوفات",

// Clinic dashboard
    "clinic.dashboard.Dashboard": "لوحة العيادة",
    "clinic.dashboard.AddReservation": "إضافة حجز",
    "clinic.dashboard.TodayReservations": "حجوزات اليوم",
    "clinic.dashboard.TotalPatients": "المرضى",
    "clinic.dashboard.RevenueMonth": "الحسابات",
    "clinic.dashboard.AvgWaitTime": "المتوسط الزمني",
    "clinic.dashboard.YouMustBeSignedInToViewTheClinicDashboard": "يجب عليك تسجيل الدخول لعرض لوحة العيادة.",
    "clinic.dashboard.SignIn": "تسجيل الدخول",
    "clinic.dashboard.ViewAll": "عرض الكل",
    "clinic.dashboard.NoReservationsToday": "لا يوجد حجوزات اليوم.",

// Clinic reservations
"clinic.reservations.Title": "حجوزات العيادة",
"clinic.reservations.Description": "حجوزات العيادة المتاحة في العيادة",
"clinic.reservations.NoReservationsFound": "لا يوجد حجوزات",
"clinic.reservations.FailedToLoadReservations": "فشل تحميل الحجوزات",
"clinic.reservations.Edit": "تعديل",
"clinic.reservations.Prescription": "الروشته",
"clinic.reservations.Glasses": "النظارات",
"clinic.reservations.Teeth": "الأسنان",
"clinic.reservations.Page": "الصفحة",
"clinic.reservations.Of": "من",
"clinic.reservations.Previous": "السابق",
"clinic.reservations.Next": "التالي",
"clinic.reservations.ForReservation": "للحجز",
"clinic.reservations.PrescriptionImages": "صور الوصف الطبي",
"clinic.reservations.Notes": "الملاحظات",
"clinic.reservations.ImagesPreview": "معاينة الصور",
"clinic.reservations.Drugs": "الأدوية",
"clinic.reservations.AddDrug": "إضافة دواء",
"clinic.reservations.Name": "الاسم",
"clinic.reservations.Type": "النوع",
"clinic.reservations.Dose": "الجرعة",
"clinic.reservations.Frequency": "التكرار",
"clinic.reservations.Period": "الفترة",
"clinic.reservations.DrugNotes": "ملاحظات الدواء",
"clinic.reservations.Cancel": "إلغاء",
"clinic.reservations.Saving": "جاري الحفظ...",
"clinic.reservations.SavePrescription": "حفظ الوصف الطبي",
"clinic.reservations.GlassesDistance": "المسافة البصرية",
"clinic.reservations.RecentRecords": "السجلات الأخيرة",
"clinic.reservations.NoGlassesRecordsYet": "لا يوجد سجلات نظارات",
"clinic.reservations.Distance": "المسافة",
"clinic.reservations.Reservations": "الحجوزات",
"clinic.reservations.AddReservation": "إضافة حجز",
"clinic.reservations.Patient": "المريض",
"clinic.reservations.Doctor": "الطبيب",
"clinic.reservations.Payment": "الدفع",
"clinic.reservations.Status": "الحالة",
"clinic.reservations.Acceptance": "القبول",
"clinic.reservations.Date": "التاريخ",
"clinic.reservations.Actions": "الإجراءات",
"clinic.reservations.ChronicDiseases": "الأمراض المزمنة",
"clinic.reservations.Control": "التحكم",
"clinic.reservations.NumberSlot": "رقم / موعد",
"clinic.reservations.LoadingReservations": "جاري تحميل الحجوزات",
"clinic.reservations.NoReservationsScheduledForToday": "لا يوجد حجوزات مجددة",
"clinic.reservations.TeethPlan": "خطة الأسنان",
"clinic.reservations.GeneralNotes": "ملاحظات عامة (اختياري)",
"clinic.reservations.FuturePlanForNextSession": "خطة المستقبل للجلسة القادمة (اختياري)",
"clinic.reservations.SelectTeethAndOptionalPerToothNotes": "اختر الأسنان والملاحظات الاختيارية لكل سن",
"clinic.reservations.UpperJaw": "الفك العلوي",
"clinic.reservations.LowerJaw": "الفك السفلي",
"clinic.reservations.SaveTeethData": "حفظ بيانات الأسنان",
"clinic.reservations.LoadingTeethData": "جاري تحميل بيانات الأسنان",
"clinic.reservations.SelectAtLeastOneTooth": "اختر على الأقل سنة واحدة",
"clinic.reservations.SaveGlassesData": "حفظ بيانات النظارات",
"clinic.reservations.LoadingGlassesData": "جاري تحميل بيانات النظارات",
"clinic.reservations.TeethNote": "ملاحظة السن",
"clinic.reservations.WriteNote": "اكتب الملاحظة",
"clinic.reservations.Optional": "اختياري",
"clinic.reservations.search": "بحث بالطبيب أو اليوم...",
"clinic.reservations.TodayReservations": "حجوزات اليوم",

    // Admin sidebar
    "admin.menu.dashboard": "الرئيسية",
    "admin.menu.clinics": "العيادات",
    "admin.menu.labs": "المعامل الطبية",
    "admin.menu.radiology": "مراكز الأشعة",
    "admin.menu.specialties": "التخصصات",
    "admin.menu.locations": "المناطق",
    "admin.menu.users": "المستخدمون والصلاحيات",
    "admin.menu.reviews": "التقييمات",
    "admin.menu.announcements": "الإعلانات",
    "admin.menu.financial": "الحسابات",

    // Lab sidebar
    "lab.menu.dashboard": "الرئيسية",
    "lab.menu.users_management": "إدارة المستخدمين",
	"lab.menu.medical_analyses_management": "إدارة التحاليل الطبية",
    "lab.menu.chat": "الدردشة",
    "lab.menu.patients": "المرضى",
    "lab.menu.users": "المستخدمون",
    "lab.menu.service_categories": "فئات الخدمات",
    "lab.menu.services": "الخدمات",
    "lab.menu.medical_analyses": "التحاليل الطبية",
    "lab.menu.financial": "الحسابات",
    "lab.menu.today_medical_analyses": "تحاليل اليوم",
    "lab.menu.roles": "الأدوار",
    "lab.menu.notifications": "الإشعارات",

	// Lab patients
	"lab.patients.title": "المرضى",
	"lab.patients.assign_existing": "تعيين موجود (كود / QR)",
	"lab.patients.add": "إضافة مريض",
	"lab.patients.patient_code": "كود المريض",
	"lab.patients.name": "الاسم",
	"lab.patients.phone": "الهاتف",
	"lab.patients.age": "العمر",
	"lab.patients.gender": "الجنس",
	"lab.patients.blood": "فصيلة الدم",
	"lab.patients.status": "الحالة",
	"lab.patients.actions": "الإجراءات",


     // Lab users
    "lab.users.title": "المستخدمون",
    "lab.users.description": "المستخدمون المعينون لهذه المنظمة المعملية",
    "lab.users.search": "بحث بالاسم أو البريد الإلكتروني أو الصلاحية...",
    "lab.users.name": "الاسم",
    "lab.users.email": "البريد الإلكتروني",
    "lab.users.permissions": "الصلاحيات",
    "lab.users.status": "الحالة",
    "lab.users.job": "الوظيفة",
"lab.users.phone": "الهاتف",
"lab.users.role": "الدور",
"lab.users.actions": "الإجراءات",
"lab.users.loading": "جاري التحميل...",
"lab.users.select_role": "اختر الدور",
"lab.users.additional_permissions": "الصلاحيات الإضافية",
"lab.users.permission": "الصلاحية",
"lab.users.delete_user": "حذف المستخدم",
"lab.users.delete_user_description": "هذا الإجراء لا يمكن التراجع عنه.",
"lab.users.deleting": "جاري الحذف...",
"lab.users.delete": "حذف",
"lab.users.cancel": "إلغاء",
"lab.users.saving": "جاري الحفظ...",
"lab.users.save": "حفظ",
"lab.users.close": "إغلاق",
"lab.users.add": "إضافة مستخدم",
"lab.users.edit": "تعديل المستخدم",
"lab.users.show": "عرض",
"lab.users.total": "الكل",
"lab.users.no_users_found": "لا يوجد مستخدمون",
"lab.users.page": "الصفحة",
"lab.users.of": "من",
"lab.users.details": "تفاصيل المستخدم",
"lab.users.activate": "تنشيط المستخدم",
"lab.users.activate_user": "تنشيط المستخدم",
"lab.users.activate_user_description": "هذا الإجراء لا يمكن التراجع عنه.",
"lab.users.leave_empty_to_keep_current_password": "اترك فارغًا للحفظ على كلمة المرور الحالية",

// Lab service categories
"lab.service_categories.title": "فئات الخدمات",
"lab.service_categories.description": "فئات الخدمات المتاحة في المعمل",
"lab.service_categories.search": "بحث باسم الفئة...",
"lab.service_categories.category": "الفئة",
"lab.service_categories.services": "الخدمات",
"lab.service_categories.status": "الحالة",
"lab.service_categories.actions": "الإجراءات",
"lab.service_categories.loading": "جاري التحميل...",
"lab.service_categories.add": "إضافة فئة",
"lab.service_categories.edit": "تعديل الفئة",
"lab.service_categories.created": "تاريخ الإنشاء",
"lab.service_categories.category_name": "اسم الفئة",
"lab.service_categories.close": "إغلاق",
"lab.service_categories.saving": "جاري الحفظ...",
"lab.service_categories.save": "حفظ",
"lab.service_categories.delete_confirmation": "هذا الإجراء لا يمكن التراجع عنه.",
"lab.service_categories.deleting": "جاري الحذف...",
"lab.service_categories.delete": "حذف",
"lab.service_categories.active": "نشط",
"lab.service_categories.inactive": "غير نشط",
"lab.service_categories.details": "تفاصيل الفئة",
"lab.service_categories.loading_categories": "جاري تحميل الفئات...",
"lab.service_categories.category_updated": "تم تحديث الفئة",
"lab.service_categories.category_deleted": "تم حذف الفئة",
"lab.service_categories.category_created": "تم إنشاء الفئة",
"lab.service_categories.failed_to_update_category": "فشل تحديث الفئة",
"lab.service_categories.failed_to_delete_category": "فشل حذف الفئة",
"lab.service_categories.category_name_required": "اسم الفئة مطلوب",

// Lab services
"lab.services.title": "الخدمات",
"lab.services.description": "الخدمات المتاحة في المعمل",
"lab.services.search": "بحث بالاسم أو الفئة أو الوحدة...",
"lab.services.category": "الفئة",
"lab.services.all_categories": "جميع الفئات",
"lab.services.name": "الاسم",
"lab.services.price": "السعر",
"lab.services.unit": "الوحدة",
"lab.services.normal_range": "المعادل الطبيعي",
"lab.services.notes": "الملاحظات",
"lab.services.close": "إغلاق",
"lab.services.saving": "جاري الحفظ...",
"lab.services.save": "حفظ",
"lab.services.delete_confirmation": "هذا الإجراء لا يمكن التراجع عنه.",
"lab.services.deleting": "جاري الحذف...",
"lab.services.delete": "حذف",
"lab.services.cancel": "إلغاء",
"lab.services.loading_services": "جاري تحميل الخدمات...",
"lab.services.failed_to_load_services": "فشل تحميل الخدمات",
"lab.services.show": "عرض",
"lab.services.edit": "تعديل",
"lab.services.add": "إضافة خدمة",
"lab.services.details": "تفاصيل الخدمة",
"lab.services.select_category": "اختر فئة",
"lab.services.actions": "الإجراءات",
"lab.services.page": "الصفحة",
"lab.services.of": "من",
"lab.services.total": "الكل",
"lab.services.active": "نشط",
"lab.services.inactive": "غير نشط",
"lab.services.delete_confirmation_description": "هذا الإجراء لا يمكن التراجع عنه.",

// Lab medical analyses
"lab.medical_analyses.title": "التحاليل الطبية",
"lab.medical_analyses.description": "التحاليل الطبية المتاحة في المعمل",
"lab.medical_analyses.no_analyses_found": "لا يوجد تحاليل",
"lab.medical_analyses.search": "بحث بالاسم أو الفئة أو الوحدة...",
"lab.medical_analyses.category": "الفئة",
"lab.medical_analyses.all_categories": "جميع الفئات",
"lab.medical_analyses.name": "الاسم",
"lab.medical_analyses.price": "السعر",
"lab.medical_analyses.unit": "الوحدة",
"lab.medical_analyses.normal_range": "المعادل الطبيعي",
"lab.medical_analyses.value": "القيمة",
"lab.medical_analyses.media": "الوسائط",
"lab.medical_analyses.notes": "الملاحظات",
"lab.medical_analyses.close": "إغلاق",
"lab.medical_analyses.saving": "جاري الحفظ...",
"lab.medical_analyses.save": "حفظ",
"lab.medical_analyses.delete_confirmation": "هذا الإجراء لا يمكن التراجع عنه.",
"lab.medical_analyses.deleting": "جاري الحذف...",
"lab.medical_analyses.delete": "حذف",
"lab.medical_analyses.cancel": "إلغاء",
"lab.medical_analyses.loading_analyses": "جاري تحميل التحاليل...",
"lab.medical_analyses.failed_to_load_analyses": "فشل تحميل التحاليل",
"lab.medical_analyses.show": "عرض",
"lab.medical_analyses.edit": "تعديل",
"lab.medical_analyses.add": "إضافة تحليل",
"lab.medical_analyses.details": "تفاصيل التحليل",
"lab.medical_analyses.actions": "الإجراءات",
"lab.medical_analyses.select_category": "اختر فئة",
"lab.medical_analyses.page": "الصفحة",
"lab.medical_analyses.of": "من",
"lab.medical_analyses.total": "الكل",
"lab.medical_analyses.active": "نشط",
"lab.medical_analyses.inactive": "غير نشط",
"lab.medical_analyses.delete_confirmation_description": "هذا الإجراء لا يمكن التراجع عنه.",
"lab.medical_analyses.patient": "المريض",
"lab.medical_analyses.date": "التاريخ",
"lab.medical_analyses.doctor": "الطبيب",
"lab.medical_analyses.payment": "الدفع",
"lab.medical_analyses.not_paid": "غير مدفوع",
"lab.medical_analyses.paid": "مدفوع",
"lab.medical_analyses.select_patient": "اختر المريض",
"lab.medical_analyses.reservation_id_optional": "رقم الحجز (اختياري)",
"lab.medical_analyses.report": "التقرير",
"lab.medical_analyses.services_values_and_media": "الخدمات والقيم والوسائط",
"lab.medical_analyses.add_service": "إضافة خدمة",
"lab.medical_analyses.service": "الخدمة",
"lab.medical_analyses.cost": "التكاليف",
"lab.medical_analyses.doctor_name": "اسم الطبيب",
"lab.medical_analyses.delete_analysis": "حذف التحليل؟",
"lab.medical_analyses.services": "الخدمات",
"lab.medical_analyses.no_services_selected": "لا يوجد خدمات محددة.",
"lab.medical_analyses.remove": "إزالة",
"lab.medical_analyses.view_file": "عرض الملف",
"lab.medical_analyses.view_file_description": "عرض الملف",
"lab.medical_analyses.delete_analysis_description": "هذا الإجراء لا يمكن التراجع عنه.",
"lab.medical_analyses.filter_doctor": "تصفية باسم الطبيب",
"lab.medical_analyses.clear_filters": "مسح الفلاتر",
"lab.medical_analyses.all_payments": "كل حالات الدفع",
"lab.medical_analyses.today_title": "تحاليل اليوم",
"lab.medical_analyses.today_description": "التحاليل الطبية الخاصة باليوم",


// lab financial
"lab.financial.title":"حسابات المعمل",
"lab.financial.description":"الإيرادات , المديونيات و اتجاهات الدفع لهذا المعمل",

    // Radiology sidebar
    "radiology.menu.dashboard": "الرئيسية",
    "radiology.menu.reservations": "الحجوزات",
    "radiology.menu.rays": "الأشعة",
    "radiology.menu.users": "المستخدمون",
    "radiology.menu.patients": "المرضى",
    "radiology.menu.roles": "الأدوار",
    "radiology.menu.financial": "الحسابات",
    "radiology.menu.notifications": "الإشعارات",

    // Patient sidebar
    "patient.menu.appointments": "المواعيد",
    "patient.menu.profile": "الملف الشخصي",
    "patient.menu.prescriptions": "الروشتات",
    "patient.menu.analyses": "التحاليل",
    "patient.menu.rays": "الأشعة",
    "patient.menu.chronic": "الأمراض المزمنة",
    "patient.menu.glasses": "نظارة المسافة",
    "patient.menu.reviews": "التقييمات",
    "patient.menu.chat": "الدردشة",

	// Shared chat
	"shared.chat.title": "الدردشة",
	"shared.chat.description": "الدردشة الحقيقية مع المرضى والمستخدمين",
	"shared.chat.search": "بحث في الدردشات",
	"shared.chat.no_conversations": "لا يوجد دردشات بعد",
	"shared.chat.patients": "المرضى",
	"shared.chat.users": "المستخدمون",
	"shared.chat.message": "الرسالة",
	"shared.chat.type_message": "اكتب رسالتك...",
	"shared.chat.no_messages": "لا يوجد رسائل بعد",
	"shared.chat.insert": "أدخل",
	"shared.chat.toggle_emoji_picker": "تبديل منشئ الرموز",
	"shared.chat.send": "إرسال",
	"shared.chat.select_or_start_conversation": "اختر أو بدء الدردشة",
  },
};

const LanguageContext = createContext<LanguageContextValue>({
  lang: "en",
  dir: "ltr",
  t: (key: string) => key,
  setLanguage: () => undefined,
  toggleLanguage: () => undefined,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    const stored = window.localStorage.getItem("lang");
    return stored === "ar" || stored === "en" ? stored : "en";
  });

  const dir: "ltr" | "rtl" = lang === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    if (typeof document !== "undefined") {
      document.documentElement.lang = lang;
      document.documentElement.dir = dir;
    }
    if (typeof window !== "undefined") {
      window.localStorage.setItem("lang", lang);
    }
  }, [lang, dir]);

  const t = (key: string) => {
    const table = translations[lang] || translations.en;
    return table[key] || key;
  };

  const setLanguage = (next: Language) => setLang(next);
  const toggleLanguage = () => setLang((prev) => (prev === "en" ? "ar" : "en"));

  return (
    <LanguageContext.Provider value={{ lang, dir, t, setLanguage, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

