import React, { createContext, useContext, useEffect, useState } from "react";

type Language = "en" | "ar";

interface LanguageContextValue {
  lang: Language;
  dir: "ltr" | "rtl";
  t: (key: string) => string;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // General
    "lang.en": "English",
    "lang.ar": "العربية",
    "nav.home": "Home",
    "nav.clinics": "Clinics",
    "nav.labs": "Labs",
    "nav.radiology": "Radiology",
    "nav.backToHome": "Back to Home",
    "auth.signIn": "Sign In",
    "auth.getStarted": "Get Started",
    "auth.login": "Log in",
    "auth.loginDescription": "Sign in to your patient account",
    "auth.register": "Register",
    "auth.registerDescription": "Create a patient account",
    "auth.logout": "Log out",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm password",
    "auth.name": "Full name",
    "auth.age": "Age",
    "auth.phone": "Phone",
    "auth.address": "Address",
    "auth.gender": "Gender",
    "auth.genderMale": "Male",
    "auth.genderFemale": "Female",
    "auth.bloodGroup": "Blood group",
    "auth.whatsapp": "WhatsApp",
    "auth.optional": "optional",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.signingIn": "Signing in…",
    "auth.creatingAccount": "Creating account…",
    "auth.passwordMismatch": "Passwords do not match",
    "auth.passwordMin": "Password must be at least 6 characters",
    "auth.dashboardLogin": "Dashboard sign in",
    "auth.dashboardLoginDescription": "Sign in to clinic, admin, lab, or radiology dashboard via the backend.",
    "auth.dashboardLoginNote": "Sign in below to access your dashboard.",
    "auth.edit": "Edit",
    "auth.backToDashboardLogin": "Back to dashboard login",
    "auth.clinicLogin": "Clinic sign in",
    "auth.clinicLoginDesc": "Sign in to your clinic dashboard",
    "auth.labLogin": "Lab sign in",
    "auth.labLoginDesc": "Sign in to your medical lab dashboard",
    "auth.radiologyLogin": "Radiology sign in",
    "auth.radiologyLoginDesc": "Sign in to your radiology center dashboard",
    "auth.clinicRegister": "Register clinic",
    "auth.clinicRegisterDesc": "Submit your clinic for approval",
    "auth.labRegister": "Register medical lab",
    "auth.labRegisterDesc": "Submit your lab for approval",
    "auth.radiologyRegister": "Register radiology center",
    "auth.radiologyRegisterDesc": "Submit your radiology center for approval",
    "auth.clinicName": "Clinic name",
    "auth.labName": "Medical lab name",
    "auth.radiologyName": "Radiology center name",
    "auth.startDate": "Start date",
    "auth.specialty": "Specialty",
    "auth.clinicEmail": "Clinic email",
    "auth.labEmail": "Lab email",
    "auth.radiologyEmail": "Radiology center email",
    "auth.select": "Select",

    // Public
    "brand.name": "Saheh",
    "public.footer.platform": "Platform",
    "public.footer.dashboards": "Dashboards",
    "public.footer.description":
      "Your trusted platform for finding clinics, doctors, and booking appointments.",
    "public.footer.clinic": "Clinic",
    "public.footer.admin": "Admin",
    "public.footer.copyright": "All rights reserved.",

    // Dashboards titles
    "clinic.title": "Clinic Dashboard",
    "admin.title": "Admin Dashboard",
    "lab.title": "Lab Dashboard",
    "radiology.title": "Radiology Dashboard",
    "patient.title": "Patient Portal",

    // Clinic sidebar
    "clinic.menu.dashboard": "Dashboard",
    "clinic.menu.reservations": "Reservations",
    "clinic.menu.drugs": "Drugs",
    "clinic.menu.questionnaires": "Questionnaires",
    "clinic.menu.reservations_management": "Reservations Management",
	"clinic.menu.clinic_management": "Clinic Management",
	"clinic.menu.users_management": "Users Management",
	"clinic.menu.users": "Users",
	"clinic.menu.roles": "Roles & Permissions",
	"clinic.menu.reviews": "Reviews",
	"clinic.menu.announcements": "Announcements",
	"clinic.menu.notifications": "Notifications",
	"clinic.menu.services": "Services",
  "clinic.menu.settings": "Settings",
	"clinic.menu.inventory": "Inventory",
	"clinic.menu.modules": "Modules",
	"clinic.menu.financial": "Financial",
	"clinic.menu.trash": "Trash",
    "clinic.menu.today": "Today",
    "clinic.menu.numbers": "Reservation Numbers",
    "clinic.menu.slots": "Reservation Slots",
    "clinic.menu.doctors": "Doctors",
    "clinic.menu.patients": "Patients",
    "clinic.menu.chat": "Chat",

    // Clinic dashboard
    "clinic.dashboard.Dashboard": "Dashboard",
    "clinic.dashboard.AddReservation": "Add Reservation",
    "clinic.dashboard.TodayReservations": "Today Reservations",
    "clinic.dashboard.TotalPatients": "Total Patients",
    "clinic.dashboard.RevenueMonth": "Revenue Month",
    "clinic.dashboard.AvgWaitTime": "Avg. Wait Time",
    "clinic.dashboard.YouMustBeSignedInToViewTheClinicDashboard": "You must be signed in to view the clinic dashboard.",
    "clinic.dashboard.SignIn": "Sign In",
    "clinic.dashboard.ViewAll": "View All",
    "clinic.dashboard.NoReservationsToday": "No reservations today.",

    // Admin sidebar
    "admin.menu.dashboard": "Dashboard",
    "admin.menu.clinics": "Clinics",
    "admin.menu.labs": "Medical Labs",
    "admin.menu.radiology": "Radiology Centers",
    "admin.menu.specialties": "Specialties",
    "admin.menu.locations": "Locations",
    "admin.menu.users": "Users & Roles",
    "admin.menu.reviews": "Reviews",
    "admin.menu.announcements": "Announcements",
    "admin.menu.financial": "Financial",

    // Lab sidebar
    "lab.menu.dashboard": "Dashboard",
    "lab.menu.users_management": "Users Management",
    "lab.menu.medical_analyses_management": "Medical Analyses Management",
    "lab.menu.chat": "Chat",
    "lab.menu.patients": "Patients",
    "lab.menu.users": "Users",
    "lab.menu.service_categories": "Service Categories",
    "lab.menu.services": "Services",
    "lab.menu.medical_analyses": "Medical Analyses",
    "lab.menu.financial": "Financial",
    "lab.menu.today_medical_analyses": "Today's Analyses",
    "lab.menu.roles": "Roles",
    "lab.menu.notifications": "Notifications",

    // Lab patients
    "lab.patients.title": "Patients",
    "lab.patients.assign_existing": "Assign Existing (Code / QR)",
    "lab.patients.add": "Add Patient",
    "lab.patients.patient_code": "Patient Code",
    "lab.patients.name": "Name",
    "lab.patients.phone": "Phone",
    "lab.patients.age": "Age",
    "lab.patients.gender": "Gender",
    "lab.patients.blood": "Blood",
    "lab.patients.status": "Status",
    "lab.patients.actions": "Actions",

    // Lab users
    "lab.users.title": "Users",
    "lab.users.description": "Users assigned to this laboratory organization",
    "lab.users.search": "Search by name, email, role...",
    "lab.users.name": "Name",
    "lab.users.email": "Email",
    "lab.users.permissions": "Permissions",
    "lab.users.status": "Status",
    "lab.users.actions": "Actions",
	"lab.users.loading": "Loading...",
	"lab.users.job": "Job Title",
	"lab.users.phone": "Phone",
	"lab.users.role": "Role",
	"lab.users.select_role": "Select Role",
	"lab.users.additional_permissions": "Additional Permissions",
	"lab.users.permission": "Permission",
	"lab.users.delete_user": "Delete User",
	"lab.users.delete_user_description": "This will deactivate the user account.",
	"lab.users.deleting": "Deleting...",
	"lab.users.delete": "Delete",
	"lab.users.cancel": "Cancel",
	"lab.users.saving": "Saving...",
	"lab.users.save": "Save",
	"lab.users.close": "Close",
	"lab.users.add": "Add User",
	"lab.users.edit": "Edit User",
	"lab.users.show": "Show",
	"lab.users.total": "Total",
	"lab.users.no_users_found": "No users found.",
	"lab.users.page": "Page",
	"lab.users.of": "of",
	"lab.users.details": "User Details",
	"lab.users.activate": "Activate",
	"lab.users.activate_user": "Activate User",
	"lab.users.activate_user_description": "This will activate the user account.",
	"lab.users.leave_empty_to_keep_current_password": "Leave empty to keep current password",

// Lab service categories
"lab.service_categories.title": "Service Categories",
"lab.service_categories.description": "Service categories available in the laboratory",
"lab.service_categories.search": "Search by category name...",
"lab.service_categories.category": "Category",
"lab.service_categories.services": "Services",
"lab.service_categories.status": "Status",
"lab.service_categories.actions": "Actions",
"lab.service_categories.loading": "Loading...",
"lab.service_categories.add": "Add Category",
"lab.service_categories.created": "Created",
"lab.service_categories.edit": "Edit Category",
"lab.service_categories.category_name": "Category Name",
"lab.service_categories.close": "Close",
"lab.service_categories.saving": "Saving...",
"lab.service_categories.save": "Save",
"lab.service_categories.delete_confirmation": "This action cannot be undone.",
"lab.service_categories.deleting": "Deleting...",
"lab.service_categories.delete": "Delete",
"lab.service_categories.active": "Active",
"lab.service_categories.inactive": "Inactive",
"lab.service_categories.details": "Category Details",
"lab.service_categories.loading_categories": "Loading categories...",
"lab.service_categories.category_updated": "Category updated",
"lab.service_categories.category_deleted": "Category deleted",
"lab.service_categories.category_created": "Category created",
"lab.service_categories.failed_to_update_category": "Failed to update category",
"lab.service_categories.failed_to_delete_category": "Failed to delete category",
"lab.service_categories.category_name_required": "Category name is required",

// Lab services
"lab.services.title": "Services",
"lab.services.description": "Services available in the laboratory",
"lab.services.search": "Search by name, category, unit...",
"lab.services.category": "Category",
"lab.services.all_categories": "All Categories",
"lab.services.name": "Name",
"lab.services.price": "Price",
"lab.services.unit": "Unit",
"lab.services.normal_range": "Normal Range",
"lab.services.notes": "Notes",
"lab.services.close": "Close",
"lab.services.saving": "Saving...",
"lab.services.save": "Save",
"lab.services.delete_confirmation": "This action cannot be undone.",
"lab.services.deleting": "Deleting...",
"lab.services.delete": "Delete",
"lab.services.cancel": "Cancel",
"lab.services.loading_services": "Loading services...",
"lab.services.failed_to_load_services": "Failed to load services",
"lab.services.show": "Show",
"lab.services.edit": "Edit",
"lab.services.add": "Add Service",
"lab.services.details": "Service Details",
"lab.services.actions": "Actions",
"lab.services.select_category": "Select Category",
"lab.services.page": "Page",
"lab.services.of": "of",
"lab.services.total": "Total",
"lab.services.active": "Active",
"lab.services.inactive": "Inactive",
"lab.services.delete_confirmation_description": "This action cannot be undone.",

// Lab medical analyses
"lab.medical_analyses.title": "Medical Analyses",
"lab.medical_analyses.description": "Medical analyses available in the laboratory",
"lab.medical_analyses.no_analyses_found": "No analyses found.",
"lab.medical_analyses.search": "Search by name, category, unit...",
"lab.medical_analyses.category": "Category",
"lab.medical_analyses.all_categories": "All Categories",
"lab.medical_analyses.name": "Name",
"lab.medical_analyses.price": "Price",
"lab.medical_analyses.unit": "Unit",
"lab.medical_analyses.normal_range": "Normal Range",
"lab.medical_analyses.notes": "Notes",
"lab.medical_analyses.close": "Close",
"lab.medical_analyses.saving": "Saving...",
"lab.medical_analyses.save": "Save",
"lab.medical_analyses.delete_confirmation": "This action cannot be undone.",
"lab.medical_analyses.deleting": "Deleting...",
"lab.medical_analyses.delete": "Delete",
"lab.medical_analyses.cancel": "Cancel",
"lab.medical_analyses.loading_analyses": "Loading analyses...",
"lab.medical_analyses.failed_to_load_analyses": "Failed to load analyses",
"lab.medical_analyses.show": "Show",
"lab.medical_analyses.edit": "Edit",
"lab.medical_analyses.add": "Add Analysis",
"lab.medical_analyses.details": "Analysis Details",
"lab.medical_analyses.actions": "Actions",
"lab.medical_analyses.select_patient": "Select Patient",
"lab.medical_analyses.date": "Date",
"lab.medical_analyses.payment": "Payment",
"lab.medical_analyses.not_paid": "Not Paid",
"lab.medical_analyses.paid": "Paid",
"lab.medical_analyses.select_payment": "Select Payment",
"lab.medical_analyses.doctor_name": "Doctor Name",
"lab.medical_analyses.reservation_id_optional": "Reservation ID (optional)",
"lab.medical_analyses.report": "Report",
"lab.medical_analyses.services_values_and_media": "Services, Values, and Media",
"lab.medical_analyses.add_service": "Add Service",
"lab.medical_analyses.remove": "Remove",
"lab.medical_analyses.view_file": "View file",
"lab.medical_analyses.no_services_selected": "No services selected.",
"lab.medical_analyses.service": "Service",
"lab.medical_analyses.value": "Value",
"lab.medical_analyses.media": "Media",
"lab.medical_analyses.cost": "Cost",
"lab.medical_analyses.select_service": "Select Service",
"lab.medical_analyses.delete_analysis": "Delete Analysis?",
"lab.medical_analyses.delete_analysis_description": "This action cannot be undone.",
"lab.medical_analyses.filter_doctor": "Filter by doctor name",
"lab.medical_analyses.clear_filters": "Clear Filters",
"lab.medical_analyses.all_payments": "All Payments",
"lab.medical_analyses.today_title": "Today's Medical Analyses",
"lab.medical_analyses.today_description": "Medical analyses created for today",
"lab.medical_analyses.services": "services",
"lab.medical_analyses.view_file_description": "View file",


"lab.financial.title":"Lab Financial",
"lab.financial.description":"Revenue, due amounts, and payment trends for this laboratory.",

// Radiology sidebar
    "radiology.menu.dashboard": "Dashboard",
    "radiology.menu.reservations": "Reservations",
    "radiology.menu.rays": "Rays",
    "radiology.menu.ray_categories": "Ray Categories",
    "radiology.menu.users": "Users",
    "radiology.menu.patients": "Patients",
    "radiology.menu.roles": "Roles",
    "radiology.menu.financial": "Financial",
    "radiology.menu.notifications": "Notifications",

    // Patient sidebar
    "patient.menu.appointments": "Appointments",
    "patient.menu.profile": "Profile",
    "patient.menu.prescriptions": "Prescriptions",
    "patient.menu.analyses": "Medical Analyses",
    "patient.menu.rays": "Rays",
    "patient.menu.chronic": "Chronic Diseases",
    "patient.menu.glasses": "Glasses Distance",
    "patient.menu.reviews": "Reviews",
    "patient.menu.reels": "Reels",
    "patient.menu.questionnaires": "Questionnaires",
    "patient.menu.chat": "Chat",

	// Shared chat
	"shared.chat.title": "Chat",
	"shared.chat.description": "Real-time organization chat with users and assigned patients",
	"shared.chat.search": "Search conversations...",
	"shared.chat.no_conversations": "No conversations yet.",
	"shared.chat.patients": "Patients",
	"shared.chat.users": "Users",
	"shared.chat.message": "Message",
	"shared.chat.type_message": "Type your message...",
	"shared.chat.select_or_start_conversation": "Select or start a conversation.",
  },
  ar: {
    "find_a_clinic": "إبحث عن عيادة",
    "my_appointments": "حجوزاتي",
	"trusted_by_patients": "موثوق بهم من قبل المرضى",
	"find_the_right_doctor_book_in_seconds": "إبحث عن الطبيب المناسب، حجز الموعد في ثوانٍ",
	"browse_clinics_compare_ratings_and_book_appointments_instantly": "تصفح العيادات، قارن التقييمات، وحجز المواعيد بشكل فوري. صحتك، بسيطة.",
	"featured_clinics": "العيادات المميزة",
	"top_rated_clinics_near_you": "العيادات التي تم تقييمها عاليا بالقرب منك",
	"view_all": "عرض الكل",
	"join_thousands_of_patients_who_trust_medicaid_for_their_healthcare_needs": "انضم إلى آلاف المرضى الذين يوثقون MediCare لاحتياجاتهم الصحية.",
	"browse_clinics": "تصفح العيادات",
	"sign_in": "تسجيل الدخول",
	"ready_to_book_your_appointment": "هل أنت جاهز لحجز موعدك؟",
    // General
    "lang.en": "English",
    "lang.ar": "العربية",
    "nav.home": "الرئيسية",
    "nav.clinics": "العيادات",
    "nav.labs": "المعامل",
    "nav.radiology": "الأشعة",
    "nav.backToHome": "العودة للرئيسية",
    "auth.signIn": "تسجيل الدخول",
    "auth.getStarted": "ابدأ الآن",
    "auth.login": "تسجيل الدخول",
    "auth.loginDescription": "سجّل الدخول إلى حساب المريض",
    "auth.register": "إنشاء حساب",
    "auth.registerDescription": "إنشاء حساب مريض",
    "auth.logout": "تسجيل الخروج",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.confirmPassword": "تأكيد كلمة المرور",
    "auth.name": "الاسم الكامل",
    "auth.age": "العمر",
    "auth.phone": "الهاتف",
    "auth.address": "العنوان",
    "auth.gender": "الجنس",
    "auth.genderMale": "ذكر",
    "auth.genderFemale": "أنثى",
    "auth.bloodGroup": "فصيلة الدم",
    "auth.whatsapp": "واتساب",
    "auth.optional": "اختياري",
    "auth.noAccount": "ليس لديك حساب؟",
    "auth.hasAccount": "لديك حساب بالفعل؟",
    "auth.signingIn": "جاري تسجيل الدخول…",
    "auth.creatingAccount": "جاري إنشاء الحساب…",
    "auth.passwordMismatch": "كلمتا المرور غير متطابقتين",
    "auth.passwordMin": "كلمة المرور 6 أحرف على الأقل",
    "auth.dashboardLogin": "تسجيل دخول لوحة التحكم",
    "auth.dashboardLoginDescription": "سجّل الدخول إلى لوحة العيادة أو الإدارة أو المعمل أو الأشعة عبر الخادم.",
    "auth.dashboardLoginNote": "سجّل الدخول أدناه للوصول إلى لوحة التحكم.",
    "auth.edit": "تعديل",
    "auth.backToDashboardLogin": "العودة لتسجيل دخول لوحة التحكم",
    "auth.clinicLogin": "تسجيل دخول العيادة",
    "auth.clinicLoginDesc": "سجّل الدخول إلى لوحة العيادة",
    "auth.labLogin": "تسجيل دخول المعمل",
    "auth.labLoginDesc": "سجّل الدخول إلى لوحة المعمل الطبي",
    "auth.radiologyLogin": "تسجيل دخول الأشعة",
    "auth.radiologyLoginDesc": "سجّل الدخول إلى لوحة مركز الأشعة",
    "auth.clinicRegister": "تسجيل عيادة",
    "auth.clinicRegisterDesc": "أرسل بيانات العيادة للمراجعة",
    "auth.labRegister": "تسجيل معمل طبي",
    "auth.labRegisterDesc": "أرسل بيانات المعمل للمراجعة",
    "auth.radiologyRegister": "تسجيل مركز أشعة",
    "auth.radiologyRegisterDesc": "أرسل بيانات مركز الأشعة للمراجعة",
    "auth.clinicName": "اسم العيادة",
    "auth.labName": "اسم المعمل الطبي",
    "auth.radiologyName": "اسم مركز الأشعة",
    "auth.startDate": "تاريخ البدء",
    "auth.specialty": "التخصص",
    "auth.clinicEmail": "بريد العيادة",
    "auth.labEmail": "بريد المعمل",
    "auth.radiologyEmail": "بريد مركز الأشعة",
    "auth.select": "اختر",

    // Public
    "brand.name": "صحيح",
    "public.footer.platform": "المنصة",
    "public.footer.dashboards": "لوحات التحكم",
    "public.footer.description":
      "منصتك الموثوقة للبحث عن العيادات والأطباء وحجز المواعيد.",
    "public.footer.clinic": "لوحة العيادة",
    "public.footer.admin": "لوحة الإدارة",
    "public.footer.copyright": "جميع الحقوق محفوظة.",

    // Dashboards titles
    "clinic.title": "لوحة العيادة",
    "admin.title": "لوحة الإدارة",
    "lab.title": "لوحة المعمل",
    "radiology.title": "لوحة الأشعة",
    "patient.title": "بوابة المريض",

    // Clinic sidebar
    "clinic.menu.dashboard": "الرئيسية",
    "clinic.menu.reservations": "الحجوزات",
    "clinic.menu.drugs": "الأدوية",
    "clinic.menu.questionnaires": "الاستبيانات",
     "clinic.menu.reservations_management": "أدارة الحجوزات",
    "clinic.menu.users_management": "إدارة المستخدمين",
    "clinic.menu.users": "المستخدمين",
    "clinic.menu.roles": "الصلاحيات والأدوار",
    "clinic.menu.clinic_management": "إدارة العيادة",
    "clinic.menu.services": "الخدمات",
    "clinic.menu.settings": "الإعدادات",
    "clinic.menu.inventory": "المخزون",
    "clinic.menu.announcements": "الإعلانات",
    "clinic.menu.reviews": "التقييمات",
    "clinic.menu.today": "حجوزات اليوم",
    "clinic.menu.numbers": "أرقام الحجز",
    "clinic.menu.slots": "مواعيد الحجز",
    "clinic.menu.doctors": "الأطباء",
    "clinic.menu.patients": "المرضى",
    "clinic.menu.chat": "المحادثات",
    "clinic.menu.notifications": "الإشعارات",
    "clinic.menu.modules": "الوحدات",
    "clinic.menu.financial": "الحسابات",
    "clinic.menu.trash": "سلة المحذوفات",

// Clinic dashboard
    "clinic.dashboard.Dashboard": "لوحة العيادة",
    "clinic.dashboard.AddReservation": "إضافة حجز",
    "clinic.dashboard.TodayReservations": "حجوزات اليوم",
    "clinic.dashboard.TotalPatients": "المرضى",
    "clinic.dashboard.RevenueMonth": "الحسابات",
    "clinic.dashboard.AvgWaitTime": "المتوسط الزمني",
    "clinic.dashboard.YouMustBeSignedInToViewTheClinicDashboard": "يجب عليك تسجيل الدخول لعرض لوحة العيادة.",
    "clinic.dashboard.SignIn": "تسجيل الدخول",
    "clinic.dashboard.ViewAll": "عرض الكل",
    "clinic.dashboard.NoReservationsToday": "لا يوجد حجوزات اليوم.",

// Clinic reservations
"clinic.reservations.Title": "حجوزات العيادة",
"clinic.reservations.Description": "حجوزات العيادة المتاحة في العيادة",
"clinic.reservations.NoReservationsFound": "لا يوجد حجوزات",
"clinic.reservations.FailedToLoadReservations": "فشل تحميل الحجوزات",
"clinic.reservations.Edit": "تعديل",
"clinic.reservations.Prescription": "الروشته",
"clinic.reservations.Glasses": "النظارات",
"clinic.reservations.Teeth": "الأسنان",
"clinic.reservations.Page": "الصفحة",
"clinic.reservations.Of": "من",
"clinic.reservations.Previous": "السابق",
"clinic.reservations.Next": "التالي",
"clinic.reservations.ForReservation": "للحجز",
"clinic.reservations.PrescriptionImages": "صور الوصف الطبي",
"clinic.reservations.Notes": "الملاحظات",
"clinic.reservations.ImagesPreview": "معاينة الصور",
"clinic.reservations.Drugs": "الأدوية",
"clinic.reservations.AddDrug": "إضافة دواء",
"clinic.reservations.Name": "الاسم",
"clinic.reservations.Type": "النوع",
"clinic.reservations.Dose": "الجرعة",
"clinic.reservations.Frequency": "التكرار",
"clinic.reservations.Period": "الفترة",
"clinic.reservations.DrugNotes": "ملاحظات الدواء",
"clinic.reservations.Cancel": "إلغاء",
"clinic.reservations.Saving": "جاري الحفظ...",
"clinic.reservations.SavePrescription": "حفظ الوصف الطبي",
"clinic.reservations.GlassesDistance": "المسافة البصرية",
"clinic.reservations.RecentRecords": "السجلات الأخيرة",
"clinic.reservations.NoGlassesRecordsYet": "لا يوجد سجلات نظارات",
"clinic.reservations.Distance": "المسافة",
"clinic.reservations.Reservations": "الحجوزات",
"clinic.reservations.AddReservation": "إضافة حجز",
"clinic.reservations.Patient": "المريض",
"clinic.reservations.Doctor": "الطبيب",
"clinic.reservations.Payment": "الدفع",
"clinic.reservations.Status": "الحالة",
"clinic.reservations.Acceptance": "القبول",
"clinic.reservations.Date": "التاريخ",
"clinic.reservations.Actions": "الإجراءات",
"clinic.reservations.ChronicDiseases": "الأمراض المزمنة",
"clinic.reservations.Control": "التحكم",
"clinic.reservations.NumberSlot": "رقم / موعد",
"clinic.reservations.LoadingReservations": "جاري تحميل الحجوزات",
"clinic.reservations.NoReservationsScheduledForToday": "لا يوجد حجوزات مجددة",
"clinic.reservations.TeethPlan": "خطة الأسنان",
"clinic.reservations.GeneralNotes": "ملاحظات عامة (اختياري)",
"clinic.reservations.FuturePlanForNextSession": "خطة المستقبل للجلسة القادمة (اختياري)",
"clinic.reservations.SelectTeethAndOptionalPerToothNotes": "اختر الأسنان والملاحظات الاختيارية لكل سن",
"clinic.reservations.UpperJaw": "الفك العلوي",
"clinic.reservations.LowerJaw": "الفك السفلي",
"clinic.reservations.SaveTeethData": "حفظ بيانات الأسنان",
"clinic.reservations.LoadingTeethData": "جاري تحميل بيانات الأسنان",
"clinic.reservations.SelectAtLeastOneTooth": "اختر على الأقل سنة واحدة",
"clinic.reservations.SaveGlassesData": "حفظ بيانات النظارات",
"clinic.reservations.LoadingGlassesData": "جاري تحميل بيانات النظارات",
"clinic.reservations.TeethNote": "ملاحظة السن",
"clinic.reservations.WriteNote": "اكتب الملاحظة",
"clinic.reservations.Optional": "اختياري",
"clinic.reservations.search": "بحث بالطبيب أو اليوم...",
"clinic.reservations.TodayReservations": "حجوزات اليوم",
"clinic.reservations.ToothNote": "ملاحظة السن",
"clinic.reservations.AddSession": "إضافة الجلسة",
"clinic.reservations.LoadingReservationSessionContext": "جاري تحميل بيانات الحجز الأساسي",
"clinic.reservations.ReservationCost": "تكلفة الحجز",
"clinic.reservations.PreviousSessions": "الجلسات السابقة",
"clinic.reservations.PaymentHistory": "سجل الدفع",
"clinic.reservations.Amount": "المبلغ",
"clinic.reservations.Remaining": "المتبقي",
"clinic.reservations.Remove": "حذف",
"clinic.reservations.Rays": "الأشعة",
"clinic.reservations.PaymentWay": "طريقة الدفع",
"clinic.reservations.Cash": "نقدي",
"clinic.reservations.Bank": "بنكي",
"clinic.reservations.CreditCard": "بطاقة ائتمان",
"clinic.reservations.DebitCard": "بطاقة ائتمان",
"clinic.reservations.Other": "أخرى",
"clinic.reservations.AddPayment": "إضافة الدفع",
"clinic.reservations.NoPaymentRowsYet": "لا يوجد صفوف دفع بعد.",
"clinic.reservations.ReservationIsAlreadyFullyPaidNoNewPaymentRequired": "الحجز مدفوع بالكامل، لا تحتاج إلى دفع جديد",
"clinic.reservations.Cancel": "إلغاء",
"clinic.reservations.CreateSession": "إنشاء الجلسة",
"clinic.reservations.LoadingPrescription": "جاري تحميل الروشتة",
"clinic.reservations.SessionReservationValue": "قيمة الحجز الأساسي للجلسة",
"clinic.reservations.ReservationNumber": "رقم الحجز",
"clinic.reservations.Slot": "موعد الحجز",
"clinic.reservations.Select": "اختر",
"clinic.reservations.Payments": "الدفعات",
"clinic.reservations.PrescriptionTitle": "عنوان الروشتة",
// clinic users
"clinic.users.title": "المستخدمون",
"clinic.users.description": "المستخدمون المعينون لهذه العيادة",
"clinic.users.search": "بحث بالاسم أو البريد الإلكتروني أو الصلاحية...",
"clinic.users.name": "الاسم",
"clinic.users.email": "البريد الإلكتروني",
"clinic.users.password": "كلمة المرور",
"clinic.users.job_title": "الوظيفة",
"clinic.users.direct_permissions": "الصلاحيات المباشرة",
"clinic.users.permissions": "الصلاحيات",
"clinic.users.status": "الحالة",
"clinic.users.job": "الوظيفة",
"clinic.users.phone": "الهاتف",
"clinic.users.role": "الدور",
"clinic.users.actions": "الإجراءات",
"clinic.users.loading": "جاري التحميل...",
"clinic.users.select_role": "اختر الدور",
"clinic.users.additional_permissions": "الصلاحيات الإضافية",
"clinic.users.permission": "الصلاحية",
"clinic.users.delete_user": "حذف المستخدم",
"clinic.users.delete_user_description": "هذا الإجراء لا يمكن التراجع عنه.",
"clinic.users.deleting": "جاري الحذف...",
"clinic.users.delete": "حذف",
"clinic.users.cancel": "إلغاء",
"clinic.users.saving": "جاري الحفظ...",
"clinic.users.save": "حفظ",
"clinic.users.close": "إغلاق",
'clinic.users.add_user': "إضافة مستخدم",
'clinic.users.edit_user': "تعديل المستخدم",
"clinic.users.add": "إضافة مستخدم",
"clinic.users.edit": "تعديل المستخدم",
"clinic.users.show": "عرض",
"clinic.users.total": "الكل",
"clinic.users.no_users_found": "لا يوجد مستخدمون",
"clinic.users.page": "الصفحة",
"clinic.users.of": "من",
"clinic.users.details": "تفاصيل المستخدم",
"clinic.users.activate": "تنشيط المستخدم",
"clinic.users.activate_user": "تنشيط المستخدم",
"clinic.users.activate_user_description": "هذا الإجراء لا يمكن التراجع عنه.",
"clinic.users.leave_empty_to_keep_current_password": "اترك فارغًا للحفظ على كلمة المرور الحالية",
"clinic.users.previous": "السابق",
"clinic.users.next": "التالي",
"clinic.users.deactivate": "تعطيل المستخدم",
"clinic.users.loading_users": "جاري التحميل...",

// clinic roles
"clinic.roles.title": "الأدوار والصلاحيات",
"clinic.roles.description": "الأدوار والصلاحيات المتاحة في العيادة",
"clinic.roles.search": "بحث بالاسم...",
"clinic.roles.name": "الاسم",
"clinic.roles.role_name": "اسم الدور",
"clinic.roles.permissions": "الصلاحيات",
"clinic.roles.actions": "الإجراءات",
"clinic.roles.loading_roles": "جاري التحميل...",
"clinic.roles.failed_to_load_roles": "فشل تحميل الأدوار والصلاحيات",
"clinic.roles.add": "إضافة الدور",
"clinic.roles.edit": "تعديل الدور",
"clinic.roles.show": "عرض الدور",
"clinic.roles.details": "تفاصيل الدور",
"clinic.roles.close": "إغلاق",
"clinic.roles.saving": "جاري الحفظ...",
"clinic.roles.save": "حفظ",
"clinic.roles.role_created": "تم إنشاء الدور",
"clinic.roles.role_updated": "تم تحديث الدور",
"clinic.roles.role_deleted": "تم حذف الدور",
"clinic.roles.role_name_is_required": "اسم الدور مطلوب",
"clinic.roles.role_name_is_required_description": "اسم الدور مطلوب",
"clinic.roles.page": "الصفحة",
"clinic.roles.of": "من",
"clinic.roles.no_roles_found": "لا يوجد أدوار وصلاحيات",

// clinic doctors
"clinic.doctors.title": "الأطباء",
"clinic.doctors.description": "الأطباء المعينون لهذه العيادة",
"clinic.doctors.search": "بحث بالاسم أو البريد الإلكتروني أو الصلاحية...",
"clinic.doctors.doctor_name": "اسم الطبيب",
"clinic.doctors.specialization": "التخصص",
"clinic.doctors.actions": "الإجراءات",
"clinic.doctors.loading": "جاري التحميل...",
"clinic.doctors.email": "البريد الإلكتروني",
"clinic.doctors.password": "كلمة المرور",
"clinic.doctors.phone": "الهاتف",
"clinic.doctors.certifications": "الشهادات",
"clinic.doctors.specializations": "التخصصات",
"clinic.doctors.loading_specializations": "جاري تحميل التخصصات...",
"clinic.doctors.select_specialization": "اختر التخصص",
"clinic.doctors.loading_doctors": "جاري تحميل الأطباء...",
"clinic.doctors.failed_to_load_doctors": "فشل تحميل الأطباء...",
"clinic.doctors.no_doctors_found": "لا يوجد أطباء",
"clinic.doctors.page": "الصفحة",
"clinic.doctors.of": "من",
"clinic.doctors.details": "تفاصيل الطبيب",
"clinic.doctors.activate": "تنشيط الطبيب",
"clinic.doctors.activate_doctor": "تنشيط الطبيب",
"clinic.doctors.activate_doctor_description": "هذا الإجراء لا يمكن التراجع عنه.",
"clinic.doctors.leave_empty_to_keep_current_password": "اترك فارغًا للحفظ على كلمة المرور الحالية",
"clinic.doctors.previous": "السابق",
"clinic.doctors.next": "التالي",
"clinic.doctors.add": "إضافة الطبيب",
"clinic.doctors.edit": "تعديل الطبيب",
"clinic.doctors.show": "عرض الطبيب",
"clinic.doctors.total": "الكل",
"clinic.doctors.close": "إغلاق",
"clinic.doctors.saving": "جاري الحفظ...",
"clinic.doctors.save": "حفظ",
"clinic.doctors.doctor_created": "تم إنشاء الطبيب",
"clinic.doctors.doctor_updated": "تم تحديث الطبيب",
"clinic.doctors.doctor_deleted": "تم حذف الطبيب",
"clinic.doctors.doctor_name_required": "اسم الطبيب مطلوب",
"clinic.doctors.doctor_name_required_description": "اسم الطبيب مطلوب",
"clinic.doctors.email_required": "البريد الإلكتروني مطلوب",
"clinic.doctors.email_required_description": "البريد الإلكتروني مطلوب",


// clinic patients
"clinic.patients.title": "المرضى",
"clinic.patients.description": "المرضى المعينون لهذه العيادة",
"clinic.patients.search": "بحث بالاسم أو الهاتف...",
"clinic.patients.patient": "المريض",
"clinic.patients.assigned_doctors": "الأطباء المعينون",
"clinic.patients.actions": "الإجراءات",
"clinic.patients.loading": "جاري التحميل...",
"clinic.patients.assign_existing_code_qr": "تعيين موجود (كود / QR)",
"clinic.patients.add_patient": "إضافة مريض",
"clinic.patients.open_full_form": "فتح النموذج الكامل",
"clinic.patients.search_by_name_or_phone": "بحث بالاسم أو الهاتف...",
"clinic.patients.name": "الاسم",
"clinic.patients.phone": "الهاتف",
"clinic.patients.address": "العنوان",
"clinic.patients.email": "البريد الإلكتروني",
"clinic.patients.gender": "الجنس",
"clinic.patients.assign_doctors": "تعيين الأطباء",
"clinic.patients.cancel": "إلغاء",
"clinic.patients.save": "حفظ",
"clinic.patients.glasses_distance": "المسافة البصرية",
"clinic.patients.loading_glasses_records": "جاري تحميل السجلات الأخيرة...",
"clinic.patients.leave_empty_if_not_linked_to_reservation": "اترك فارغًا إذا لم يكن مرتبطًا بحجز",
"clinic.patients.recent_records": "السجلات الأخيرة",
"clinic.patients.no_glasses_records_yet": "لا يوجد سجلات نظارات بعد.",
"clinic.patients.assign": "تعيين",
"clinic.patients.failed_to_save_glasses_distance": "فشل حفظ المسافة البصرية",
"clinic.patients.failed_to_load_glasses_records": "فشل تحميل السجلات الأخيرة",
"clinic.patients.cannot_start_camera_scan": "فشل بدء المسح بالكاميرا",
"clinic.patients.assign_existing_patient": "تعيين موجود",
"clinic.patients.patient_code": "كود المريض",
"clinic.patients.qr_value": "قيمة الQR (النص المسح)",
"clinic.patients.scan_with_camera": "مسح بالكاميرا",
"clinic.patients.start_camera_scan": "بدء المسح بالكاميرا",
"clinic.patients.stop_camera": "إيقاف المسح بالكاميرا",
"clinic.patients.reservation": "الحجز",
"clinic.patients.reservation_id": "رقم الحجز",
"clinic.patients.distance": "المسافة",
"clinic.patients.failed_to_load_patients": "فشل تحميل المرضى",
"clinic.patients.no_patients_found": "لا يوجد مرضى",
"clinic.patients.loading_patients": "جاري تحميل المرضى",
"clinic.patients.edit": "تعديل المريض",
"clinic.patients.history": "السجلات",
"clinic.patients.add_reservation": "إضافة حجز",
"clinic.patients.glasses": "النظارات",
"clinic.patients.patient_updated": "تم تحديث المريض",
"clinic.patients.patient_created": "تم إنشاء المريض",
"clinic.patients.failed_to_save_patient": "فشل حفظ المريض",
"clinic.patients.missing_required_fields": "مفقود الحقول المطلوبة",
"clinic.patients.at_least_one_doctor_name_address_phone_and_gender_are_required": "يجب أن يكون لديك على الأقل طبيب واحد واسم وعنوان وهاتف وجنس",
"clinic.patients.create": "إنشاء مريض",
"clinic.patients.back": "السابق",
"clinic.patients.assigned_doctors": "الأطباء المعينون",
"clinic.patients.no_doctors_available": "لا يوجد أطباء متاحين.",
"clinic.patients.patient_name": "اسم المريض",
"clinic.patients.password": "كلمة المرور",
"clinic.patients.optional": "اختياري",
"clinic.patients.whatsapp_number": "رقم الواتساب",
"clinic.patients.age": "العمر",
"clinic.patients.gender": "الجنس",
"clinic.patients.blood_type": "فصيلة الدم",
"clinic.patients.select_blood_type": "اختر فصيلة الدم",
"clinic.patients.not_set": "غير محدد",
"clinic.patients.height": "الطول",
"clinic.patients.weight": "الوزن",
'clinic.patients.male': 'ذكر',
'clinic.patients.female': 'أنثى',
"clinic.patients.scanned_text": "النص المسح",
"clinic.patients.paste_scanned_qr_content": "ألصق النص المسح",
"clinic.patients.saving": "جاري الحفظ...",
"clinic.patients.save_changes": "حفظ التعديلات",
"clinic.patients.create_patient": "إنشاء مريض",


// clinic reservations numbers
"clinic.reservations-numbers.title": "أرقام الحجوزات",
"clinic.reservations-numbers.description": "أرقام الحجوزات المتاحة في العيادة",
"clinic.reservations-numbers.search": "بحث بالطبيب أو اليوم...",
"clinic.reservations-numbers.doctor": "الطبيب",
"clinic.reservations-numbers.date": "اليوم",
"clinic.reservations-numbers.reservations_count": "عدد الحجوزات",
"clinic.reservations-numbers.close": "إغلاق",
"clinic.reservations-numbers.save": "حفظ",
"clinic.reservations-numbers.add_reservation_number": "إضافة رقم حجز",
"clinic.reservations-numbers.edit_reservation_number": "تعديل رقم حجز",
"clinic.reservations-numbers.reservation_number_details": "تفاصيل رقم الحجز",
"clinic.reservations-numbers.select_doctor": "اختر الطبيب",
"clinic.reservations-numbers.previous": "السابق",
"clinic.reservations-numbers.next": "التالي",
"clinic.reservations-numbers.page": "الصفحة",
"clinic.reservations-numbers.of": "من",
"clinic.reservations-numbers.no_data_found": "لا يوجد بيانات",
"clinic.reservations-numbers.failed_to_load_reservation_numbers": "فشل تحميل أرقام الحجوزات",
"clinic.reservations-numbers.reservation_number_row_added_in_dashboard_view": "تم إضافة رقم حجز في عرض اللوحة الرئيسية.",
"clinic.reservations-numbers.reservation_number_row_updated_in_dashboard_view": "تم تحديث رقم حجز في عرض اللوحة الرئيسية.",
"clinic.reservations-numbers.add": "إضافة",
"clinic.reservations-numbers.edit": "تعديل",
"clinic.reservations-numbers.show": "عرض",
"clinic.reservations-numbers.missing_required_fields": "مفقود الحقول المطلوبة",
"clinic.reservations-numbers.doctor_and_date_are_required": "يجب أن يكون لديك طبيب ويوم",
"clinic.reservations-numbers.added": "تم إضافة رقم حجز",
"clinic.reservations-numbers.updated": "تم تحديث رقم حجز",
"clinic.reservations-numbers.actions": "الإجراءات",
"clinic.reservations-numbers.loading": "جاري التحميل...",
"clinic.reservations-numbers.search_by_doctor_or_day": "بحث بالطبيب أو اليوم...",
"clinic.reservations-numbers.loading_reservation_numbers": "جاري تحميل أرقام الحجوزات...",
   
// clinic reservations slots
"clinic.reservations-slots.title": "حجوزات المواعيد",
"clinic.reservations-slots.description": "حجوزات المواعيد المتاحة في العيادة",
"clinic.reservations-slots.search": "بحث بالطبيب أو اليوم...",
"clinic.reservations-slots.doctor": "الطبيب",
"clinic.reservations-slots.date": "اليوم",
"clinic.reservations-slots.start": "البدء",
"clinic.reservations-slots.end": "النهاية",
"clinic.reservations-slots.duration_min": "المدة المتوقعة (دقيقة)",
"clinic.reservations-slots.close": "إغلاق",
"clinic.reservations-slots.save": "حفظ",
"clinic.reservations-slots.add_slot": "إضافة موعد",
"clinic.reservations-slots.edit_slot": "تعديل الموعد",
"clinic.reservations-slots.slot_details": "تفاصيل الموعد",
"clinic.reservations-slots.select_doctor": "اختر الطبيب",
"clinic.reservations-slots.previous": "السابق",
"clinic.reservations-slots.next": "التالي",
"clinic.reservations-slots.page": "الصفحة",
"clinic.reservations-slots.of": "من",
"clinic.reservations-slots.no_data_found": "لا يوجد بيانات",
"clinic.reservations-slots.failed_to_load_reservation_slots": "فشل تحميل حجوزات المواعيد",
"clinic.reservations-slots.reservation_slot_row_added_in_dashboard_view": "تم إضافة حجز موعد في عرض اللوحة الرئيسية.",
"clinic.reservations-slots.reservation_slot_row_updated_in_dashboard_view": "تم تحديث حجز موعد في عرض اللوحة الرئيسية.",
"clinic.reservations-slots.added": "تم إضافة حجز موعد",
"clinic.reservations-slots.updated": "تم تحديث حجز موعد",
"clinic.reservations-slots.actions": "الإجراءات",
"clinic.reservations-slots.loading": "جاري التحميل...",
"clinic.reservations-slots.search_by_doctor_or_day": "بحث بالطبيب أو اليوم...",
"clinic.reservations-slots.loading_reservation_slots": "جاري تحميل حجوزات المواعيد...",
"clinic.reservations-slots.missing_required_fields": "مفقود الحقول المطلوبة",
"clinic.reservations-slots.doctor_and_date_are_required": "يجب أن يكون لديك طبيب ويوم",
"clinic.reservations-slots.table_with_add_show_and_edit_dialogs": "جدول بإضافة، عرض، وتعديل الحوارات",
"clinic.reservations-slots.add": "إضافة",
"clinic.reservations-slots.show": "عرض",
"clinic.reservations-slots.edit": "تعديل",
"clinic.reservations-slots.duration_min": "المدة المتوقعة (دقيقة)",
"clinic.reservations-slots.close": "إغلاق",
"clinic.reservations-slots.save": "حفظ",


// clinic services
"clinic.services.title": "الخدمات",
"clinic.services.description": "الخدمات المتاحة في العيادة",
"clinic.services.search": "بحث بالاسم أو النوع أو الطبيب...",
"clinic.services.name": "الاسم",
"clinic.services.type": "النوع",
"clinic.services.price": "السعر",
"clinic.services.notes": "الملاحظات",
"clinic.services.doctor": "الطبيب",
"clinic.services.select_doctor": "اختر الطبيب",
"clinic.services.main": "رئيسي",
"clinic.services.sub": "فرعي",
"clinic.services.service_added": "تم إضافة الخدمة",
"clinic.services.service_updated": "تم تحديث الخدمة",
"clinic.services.actions": "الإجراءات",
"clinic.services.close": "إغلاق",
"clinic.services.save": "حفظ",
"clinic.services.add": "إضافة خدمة",
"clinic.services.edit": "تعديل الخدمة",
"clinic.services.show": "عرض الخدمة",
"clinic.services.instructions": "التعليمات",
"clinic.services.instructions_count": "عدد التعليمات",
"clinic.services.instructions_count_placeholder": "عدد التعليمات (0)",
"clinic.services.instructions_count_placeholder": "عدد التعليمات (0)",
"clinic.services.service_details": "تفاصيل الخدمة",
"clinic.services.service_name": "اسم الخدمة",
"clinic.services.service_name_is_required": "اسم الخدمة مطلوب",
"clinic.services.price_must_be_a_valid_non_negative_number": "السعر يجب أن يكون رقم غير سالب",
"clinic.services.loading_services": "جاري تحميل الخدمات...",
"clinic.services.failed_to_load_services": "فشل تحميل الخدمات...",
"clinic.services.no_services_found": "لا يوجد خدمات",
"clinic.services.search_by_name_type_or_doctor": "بحث بالاسم أو النوع أو الطبيب...",
"clinic.services.previous": "السابق",
"clinic.services.next": "التالي",
"clinic.services.page": "الصفحة",
"clinic.services.of": "من",
"clinic.services.total": "الكل",
"clinic.services.active": "نشط",
"clinic.services.inactive": "غير نشط",
"clinic.services.delete_confirmation_description": "هذا الإجراء لا يمكن التراجع عنه.",
"clinic.services.delete_confirmation": "هذا الإجراء لا يمكن التراجع عنه.",
"clinic.services.deleting": "جاري الحذف...",
"clinic.services.delete": "حذف",
"clinic.services.cancel": "إلغاء",
'clinic.services.save_instructions': "حفظ التعليمات",

// clinic settings
"clinic.settings.title": "إعدادات العيادة",
"clinic.settings.description": "إعدادات العيادة المتاحة في العيادة",
"clinic.settings.search": "بحث بالاسم أو البريد الإلكتروني أو الهاتف...",
"clinic.settings.name": "الاسم",
"clinic.settings.email": "البريد الإلكتروني",
"clinic.settings.phone": "الهاتف",
"clinic.settings.website": "عنوان الموقع",
"clinic.settings.specialty": "التخصص",
"clinic.settings.select_specialty": "اختر التخصص",
"clinic.settings.governorate": "المحافظة",
"clinic.settings.select_governorate": "اختر المحافظة",
"clinic.settings.city": "المدينة",
"clinic.settings.select_city": "اختر المدينة",
"clinic.settings.area": "المنطقة",
"clinic.settings.select_area": "اختر المنطقة",
"clinic.settings.address": "العنوان",
"clinic.settings.description": "الوصف",
"clinic.settings.saving": "جاري الحفظ...",
"clinic.settings.save_changes": "حفظ التعديلات",
"clinic.settings.close": "إغلاق",
"clinic.settings.save": "حفظ",
"clinic.settings.add": "إضافة",
"clinic.settings.edit": "تعديل",
"clinic.settings.show": "عرض",
"clinic.settings.none": "غير محدد",
"clinic.settings.loading_settings": "جاري تحميل إعدادات العيادة...",
"clinic.settings.failed_to_load_settings": "فشل تحميل إعدادات العيادة...",
"clinic.settings.no_settings_found": "لا يوجد إعدادات",
"clinic.settings.search_by_name_email_or_phone": "بحث بالاسم أو البريد الإلكتروني أو الهاتف...",
"clinic.settings.clinic_logo": "شعار العيادة",
"clinic.settings.png_jpg_up_to_4mb": "PNG/JPG حتى 4MB.",

// clinic inventory
"clinic.inventory.title": "المخزون",
"clinic.inventory.description": "المخزون المتاح في العيادة",
"clinic.inventory.search": "بحث بالاسم أو النوع أو الكمية...",
"clinic.inventory.name": "الاسم",
"clinic.inventory.quantity": "الكمية",
"clinic.inventory.price": "السعر",
"clinic.inventory.type": "النوع",
"clinic.inventory.date": "التاريخ",

"clinic.inventory.categories": "الفئات",
"clinic.inventory.movements": "الحركات",
"clinic.inventory.category": "الفئة",
"clinic.inventory.movement": "الحركة",
"clinic.inventory.item": "العنصر",
"clinic.inventory.type": "النوع",
"clinic.inventory.quantity": "الكمية",
"clinic.inventory.date": "التاريخ",
"clinic.inventory.close": "إغلاق",
"clinic.inventory.save": "حفظ",
"clinic.inventory.add": "إضافة",
"clinic.inventory.edit": "تعديل",
"clinic.inventory.show": "عرض",
"clinic.inventory.none": "غير محدد",
"clinic.inventory.loading_categories": "جاري تحميل الفئات...",
"clinic.inventory.failed_to_load_categories": "فشل تحميل الفئات...",
"clinic.inventory.no_categories_found": "لا يوجد فئات",
"clinic.inventory.loading_movements": "جاري تحميل الحركات...",
"clinic.inventory.no_movements_found": "لا يوجد حركات",
"clinic.inventory.failed_to_load_movements": "فشل تحميل الحركات...",
"clinic.inventory.details": "تفاصيل الفئة",
"clinic.inventory.category_details": "تفاصيل الفئة",
"clinic.inventory.movement_details": "تفاصيل الحركة",
"clinic.inventory.category_updated": "تم تحديث الفئة",
"clinic.inventory.movement_updated": "تم تحديث الحركة",
"clinic.inventory.category_deleted": "تم حذف الفئة",
"clinic.inventory.movement_deleted": "تم حذف الحركة",

// clinic reviews
"clinic.reviews.title": "التقييمات",
"clinic.reviews.description": "التقييمات المتاحة في العيادة",
"clinic.reviews.search": "بحث بالمريض أو التقييم أو الحالة...",
"clinic.reviews.patient": "المريض",
"clinic.reviews.rating": "التقييم",
"clinic.reviews.status": "الحالة",
"clinic.reviews.comment": "التقييم",
"clinic.reviews.close": "إغلاق",
"clinic.reviews.save": "حفظ",
"clinic.reviews.add": "إضافة التقييم",
"clinic.reviews.edit": "تعديل التقييم",
"clinic.reviews.details": "تفاصيل التقييم",
"clinic.reviews.loading_reviews": "جاري تحميل التقييمات...",
"clinic.reviews.failed_to_load_reviews": "فشل تحميل التقييمات...",
"clinic.reviews.no_reviews_found": "لا يوجد تقييمات",
"clinic.reviews.previous": "السابق",
"clinic.reviews.next": "التالي",
"clinic.reviews.page": "الصفحة",
"clinic.reviews.of": "من",
"clinic.reviews.total": "الكل",
"clinic.reviews.active": "نشط",
"clinic.reviews.inactive": "غير نشط",
"clinic.reviews.delete_confirmation_description": "هذا الإجراء لا يمكن التراجع عنه.",
"clinic.reviews.delete_confirmation": "هذا الإجراء لا يمكن التراجع عنه.",
"clinic.reviews.deleting": "جاري الحذف...",
"clinic.reviews.delete": "حذف",
"clinic.reviews.cancel": "إلغاء",
"clinic.reviews.saving": "جاري الحفظ...",
"clinic.reviews.save": "حفظ",
"clinic.reviews.close": "إغلاق",
"clinic.reviews.actions": "الإجراءات",

// clinic announcements

"clinic.announcements.title": "الإعلانات",
"clinic.announcements.description": "الإعلانات المتاحة في العيادة",
"clinic.announcements.search": "بحث بالاسم أو المحتوى أو الحالة...",
"clinic.announcements.title": "الاسم",
"clinic.announcements.content": "المحتوى",
"clinic.announcements.audience": "الجمهور",
"clinic.announcements.channel": "القناة",
"clinic.announcements.status": "الحالة",
"clinic.announcements.actions": "الإجراءات",
"clinic.announcements.close": "إغلاق",
"clinic.announcements.save": "حفظ",
"clinic.announcements.add": "إضافة إعلان",
"clinic.announcements.edit": "تعديل الإعلان",
"clinic.announcements.details": "تفاصيل الإعلان",
"clinic.announcements.loading_announcements": "جاري تحميل الإعلانات...",
"clinic.announcements.failed_to_load_announcements": "فشل تحميل الإعلانات...",
"clinic.announcements.no_announcements_found": "لا يوجد إعلانات",
"clinic.announcements.previous": "السابق",
"clinic.announcements.next": "التالي",
"clinic.announcements.page": "الصفحة",
"clinic.announcements.of": "من",
"clinic.announcements.total": "الكل",
"clinic.announcements.active": "نشط",
"clinic.announcements.inactive": "غير نشط",
"clinic.announcements.delete_confirmation_description": "هذا الإجراء لا يمكن التراجع عنه.",
"clinic.announcements.delete_confirmation": "هذا الإجراء لا يمكن التراجع عنه.",
"clinic.announcements.deleting": "جاري الحذف...",
"clinic.announcements.delete": "حذف",
"clinic.announcements.cancel": "إلغاء",
"clinic.announcements.saving": "جاري الحفظ...",
"clinic.announcements.save": "حفظ",
"clinic.announcements.close": "إغلاق",


// clinic drugs
"clinic.drugs.title": "الأدوية",
"clinic.drugs.description": "الأدوية المتاحة في العيادة",
"clinic.drugs.search": "بحث بالاسم أو النوع أو الجرعة أو الدكتور...",
"clinic.drugs.name": "الاسم",
"clinic.drugs.type": "النوع",
"clinic.drugs.dose": "الجرعة",
"clinic.drugs.frequency": "التكرار",
"clinic.drugs.period": "الفترة",
"clinic.drugs.notes": "الملاحظات",
"clinic.drugs.doctor":"الطبيب",
"clinic.drugs.actions":"الأجراءات",
"clinic.drugs.no_drugs_found":"الأدوية غير موجوده",
"clinic.drugs.add":"أضافة",
"clinic.drugs.edit":"تعديل",
"clinic.drugs.delete":"حذف",
"clinic.drugs.select_doctor":"أختار الطبيب",
"clinic.drugs.save":"حفظ",
"clinic.drugs.close":"أغلاق",
"clinic.drugs.loading":"تحميل الأدوية",

// clinic questionnaires
"clinic.questionnaires":"الاستبيانات",
"clinic.questionnaires.title":"العنوان",
"clinic.questionnaires.questions":"الأسئلة",
"clinic.questionnaires.status":"الحالة",
"clinic.questionnaires.type":"النوع",
"clinic.questionnaires.sort":"الترتيب",
"clinic.questionnaires.placeholder":"placeholder",
"clinic.questionnaires.required":"المطلوب",
"clinic.questionnaires.options_comma_separated":"الخيارات (مفصولة بفواصل)",
"clinic.questionnaires.add_question":"إضافة سؤال",
"clinic.questionnaires.add_questionnaire":"إضافة استبيان",
"clinic.questionnaires.search_questionnaires":"بحث في الاستبيانات",
"clinic.questionnaires.questionnaire_created":"تم إنشاء الاستبيان",
"clinic.questionnaires.questionnaire_updated":"تم تحديث الاستبيان",
"clinic.questionnaires.questionnaire_deleted":"تم حذف الاستبيان",
"clinic.questionnaires.failed_to_delete_questionnaire":"فشل حذف الاستبيان",
"clinic.questionnaires.title_is_required":"العنوان مطلوب",
"clinic.questionnaires.at_least_one_question_is_required":"يجب أن يكون لديك سؤال واحد على الأقل",
"clinic.questionnaires.all_question_texts_are_required":"يجب أن يكون لديك نص لكل سؤال",
"clinic.questionnaires.choice_questions_require_options":"يجب أن يكون لديك خيارات للأسئلة المتعددة الخيارات",
"clinic.questionnaires.questionnaire_answers":"الإجابات على الاستبيان",
"clinic.questionnaires.no_answers_yet":"لا يوجد إجابات على الاستبيان",
"clinic.questionnaires.loading_answers":"جاري تحميل الإجابات",
"clinic.questionnaires.unknown_patient":"المريض غير معروف",
"clinic.questionnaires.question":"السؤال",
"clinic.questionnaires.yes":"نعم",
"clinic.questionnaires.no":"لا",
"clinic.questionnaires.actions":"الأجراءات",
"clinic.questionnaires.active":"نشط",
"clinic.questionnaires.loading_questionnaires":"تحميل الأستبيانات",
"clinic.questionnaires.loading_questionnaire":"تحميل الأستبيان",
"clinic.questionnaires.show":"عرض",
"clinic.questionnaires.edit":"تعديل",
"clinic.questionnaires.answers":"الأجابات",
"clinic.questionnaires.delete":"حذف",
"clinic.questionnaires.questionnaire_details":"تفاصيل الأستبيان",
"clinic.questionnaires.close":"أغلاق",
"clinic.questionnaires.save":"حفظ",
"clinic.questionnaires.description":"الوصف",
"clinic.questionnaires.edit_questionnaire":"تعديل الأستبيان",
"":"",
"":"",
"":"",
"":"",
"":"",
"":"",
"":"",


 // Admin sidebar
    "admin.menu.dashboard": "الرئيسية",
    "admin.menu.clinics": "العيادات",
    "admin.menu.labs": "المعامل الطبية",
    "admin.menu.radiology": "مراكز الأشعة",
    "admin.menu.specialties": "التخصصات",
    "admin.menu.locations": "المناطق",
    "admin.menu.users": "المستخدمون والصلاحيات",
    "admin.menu.reviews": "التقييمات",
    "admin.menu.announcements": "الإعلانات",
    "admin.menu.financial": "الحسابات",

    // Lab sidebar
    "lab.menu.dashboard": "الرئيسية",
    "lab.menu.users_management": "إدارة المستخدمين",
	"lab.menu.medical_analyses_management": "إدارة التحاليل الطبية",
    "lab.menu.chat": "الدردشة",
    "lab.menu.patients": "المرضى",
    "lab.menu.users": "المستخدمون",
    "lab.menu.service_categories": "فئات الخدمات",
    "lab.menu.services": "الخدمات",
    "lab.menu.medical_analyses": "التحاليل الطبية",
    "lab.menu.financial": "الحسابات",
    "lab.menu.today_medical_analyses": "تحاليل اليوم",
    "lab.menu.roles": "الأدوار",
    "lab.menu.notifications": "الإشعارات",

	// Lab patients
	"lab.patients.title": "المرضى",
	"lab.patients.assign_existing": "تعيين موجود (كود / QR)",
	"lab.patients.add": "إضافة مريض",
	"lab.patients.patient_code": "كود المريض",
	"lab.patients.name": "الاسم",
	"lab.patients.phone": "الهاتف",
	"lab.patients.age": "العمر",
	"lab.patients.gender": "الجنس",
	"lab.patients.blood": "فصيلة الدم",
	"lab.patients.status": "الحالة",
	"lab.patients.actions": "الإجراءات",


     // Lab users
    "lab.users.title": "المستخدمون",
    "lab.users.description": "المستخدمون المعينون لهذه المنظمة المعملية",
    "lab.users.search": "بحث بالاسم أو البريد الإلكتروني أو الصلاحية...",
    "lab.users.name": "الاسم",
    "lab.users.email": "البريد الإلكتروني",
    "lab.users.permissions": "الصلاحيات",
    "lab.users.status": "الحالة",
    "lab.users.job": "الوظيفة",
"lab.users.phone": "الهاتف",
"lab.users.role": "الدور",
"lab.users.actions": "الإجراءات",
"lab.users.loading": "جاري التحميل...",
"lab.users.select_role": "اختر الدور",
"lab.users.additional_permissions": "الصلاحيات الإضافية",
"lab.users.permission": "الصلاحية",
"lab.users.delete_user": "حذف المستخدم",
"lab.users.delete_user_description": "هذا الإجراء لا يمكن التراجع عنه.",
"lab.users.deleting": "جاري الحذف...",
"lab.users.delete": "حذف",
"lab.users.cancel": "إلغاء",
"lab.users.saving": "جاري الحفظ...",
"lab.users.save": "حفظ",
"lab.users.close": "إغلاق",
"lab.users.add": "إضافة مستخدم",
"lab.users.edit": "تعديل المستخدم",
"lab.users.show": "عرض",
"lab.users.total": "الكل",
"lab.users.no_users_found": "لا يوجد مستخدمون",
"lab.users.page": "الصفحة",
"lab.users.of": "من",
"lab.users.details": "تفاصيل المستخدم",
"lab.users.activate": "تنشيط المستخدم",
"lab.users.activate_user": "تنشيط المستخدم",
"lab.users.activate_user_description": "هذا الإجراء لا يمكن التراجع عنه.",
"lab.users.leave_empty_to_keep_current_password": "اترك فارغًا للحفظ على كلمة المرور الحالية",

// Lab service categories
"lab.service_categories.title": "فئات الخدمات",
"lab.service_categories.description": "فئات الخدمات المتاحة في المعمل",
"lab.service_categories.search": "بحث باسم الفئة...",
"lab.service_categories.category": "الفئة",
"lab.service_categories.services": "الخدمات",
"lab.service_categories.status": "الحالة",
"lab.service_categories.actions": "الإجراءات",
"lab.service_categories.loading": "جاري التحميل...",
"lab.service_categories.add": "إضافة فئة",
"lab.service_categories.edit": "تعديل الفئة",
"lab.service_categories.created": "تاريخ الإنشاء",
"lab.service_categories.category_name": "اسم الفئة",
"lab.service_categories.close": "إغلاق",
"lab.service_categories.saving": "جاري الحفظ...",
"lab.service_categories.save": "حفظ",
"lab.service_categories.delete_confirmation": "هذا الإجراء لا يمكن التراجع عنه.",
"lab.service_categories.deleting": "جاري الحذف...",
"lab.service_categories.delete": "حذف",
"lab.service_categories.active": "نشط",
"lab.service_categories.inactive": "غير نشط",
"lab.service_categories.details": "تفاصيل الفئة",
"lab.service_categories.loading_categories": "جاري تحميل الفئات...",
"lab.service_categories.category_updated": "تم تحديث الفئة",
"lab.service_categories.category_deleted": "تم حذف الفئة",
"lab.service_categories.category_created": "تم إنشاء الفئة",
"lab.service_categories.failed_to_update_category": "فشل تحديث الفئة",
"lab.service_categories.failed_to_delete_category": "فشل حذف الفئة",
"lab.service_categories.category_name_required": "اسم الفئة مطلوب",

// Lab services
"lab.services.title": "الخدمات",
"lab.services.description": "الخدمات المتاحة في المعمل",
"lab.services.search": "بحث بالاسم أو الفئة أو الوحدة...",
"lab.services.category": "الفئة",
"lab.services.all_categories": "جميع الفئات",
"lab.services.name": "الاسم",
"lab.services.price": "السعر",
"lab.services.unit": "الوحدة",
"lab.services.normal_range": "المعادل الطبيعي",
"lab.services.notes": "الملاحظات",
"lab.services.close": "إغلاق",
"lab.services.saving": "جاري الحفظ...",
"lab.services.save": "حفظ",
"lab.services.delete_confirmation": "هذا الإجراء لا يمكن التراجع عنه.",
"lab.services.deleting": "جاري الحذف...",
"lab.services.delete": "حذف",
"lab.services.cancel": "إلغاء",
"lab.services.loading_services": "جاري تحميل الخدمات...",
"lab.services.failed_to_load_services": "فشل تحميل الخدمات",
"lab.services.show": "عرض",
"lab.services.edit": "تعديل",
"lab.services.add": "إضافة خدمة",
"lab.services.details": "تفاصيل الخدمة",
"lab.services.select_category": "اختر فئة",
"lab.services.actions": "الإجراءات",
"lab.services.page": "الصفحة",
"lab.services.of": "من",
"lab.services.total": "الكل",
"lab.services.active": "نشط",
"lab.services.inactive": "غير نشط",
"lab.services.delete_confirmation_description": "هذا الإجراء لا يمكن التراجع عنه.",

// Lab medical analyses
"lab.medical_analyses.title": "التحاليل الطبية",
"lab.medical_analyses.description": "التحاليل الطبية المتاحة في المعمل",
"lab.medical_analyses.no_analyses_found": "لا يوجد تحاليل",
"lab.medical_analyses.search": "بحث بالاسم أو الفئة أو الوحدة...",
"lab.medical_analyses.category": "الفئة",
"lab.medical_analyses.all_categories": "جميع الفئات",
"lab.medical_analyses.name": "الاسم",
"lab.medical_analyses.price": "السعر",
"lab.medical_analyses.unit": "الوحدة",
"lab.medical_analyses.normal_range": "المعادل الطبيعي",
"lab.medical_analyses.value": "القيمة",
"lab.medical_analyses.media": "الوسائط",
"lab.medical_analyses.notes": "الملاحظات",
"lab.medical_analyses.close": "إغلاق",
"lab.medical_analyses.saving": "جاري الحفظ...",
"lab.medical_analyses.save": "حفظ",
"lab.medical_analyses.delete_confirmation": "هذا الإجراء لا يمكن التراجع عنه.",
"lab.medical_analyses.deleting": "جاري الحذف...",
"lab.medical_analyses.delete": "حذف",
"lab.medical_analyses.cancel": "إلغاء",
"lab.medical_analyses.loading_analyses": "جاري تحميل التحاليل...",
"lab.medical_analyses.failed_to_load_analyses": "فشل تحميل التحاليل",
"lab.medical_analyses.show": "عرض",
"lab.medical_analyses.edit": "تعديل",
"lab.medical_analyses.add": "إضافة تحليل",
"lab.medical_analyses.details": "تفاصيل التحليل",
"lab.medical_analyses.actions": "الإجراءات",
"lab.medical_analyses.select_category": "اختر فئة",
"lab.medical_analyses.page": "الصفحة",
"lab.medical_analyses.of": "من",
"lab.medical_analyses.total": "الكل",
"lab.medical_analyses.active": "نشط",
"lab.medical_analyses.inactive": "غير نشط",
"lab.medical_analyses.delete_confirmation_description": "هذا الإجراء لا يمكن التراجع عنه.",
"lab.medical_analyses.patient": "المريض",
"lab.medical_analyses.date": "التاريخ",
"lab.medical_analyses.doctor": "الطبيب",
"lab.medical_analyses.payment": "الدفع",
"lab.medical_analyses.not_paid": "غير مدفوع",
"lab.medical_analyses.paid": "مدفوع",
"lab.medical_analyses.select_patient": "اختر المريض",
"lab.medical_analyses.reservation_id_optional": "رقم الحجز (اختياري)",
"lab.medical_analyses.report": "التقرير",
"lab.medical_analyses.services_values_and_media": "الخدمات والقيم والوسائط",
"lab.medical_analyses.add_service": "إضافة خدمة",
"lab.medical_analyses.service": "الخدمة",
"lab.medical_analyses.cost": "التكاليف",
"lab.medical_analyses.doctor_name": "اسم الطبيب",
"lab.medical_analyses.delete_analysis": "حذف التحليل؟",
"lab.medical_analyses.services": "الخدمات",
"lab.medical_analyses.no_services_selected": "لا يوجد خدمات محددة.",
"lab.medical_analyses.remove": "إزالة",
"lab.medical_analyses.view_file": "عرض الملف",
"lab.medical_analyses.view_file_description": "عرض الملف",
"lab.medical_analyses.delete_analysis_description": "هذا الإجراء لا يمكن التراجع عنه.",
"lab.medical_analyses.filter_doctor": "تصفية باسم الطبيب",
"lab.medical_analyses.clear_filters": "مسح الفلاتر",
"lab.medical_analyses.all_payments": "كل حالات الدفع",
"lab.medical_analyses.today_title": "تحاليل اليوم",
"lab.medical_analyses.today_description": "التحاليل الطبية الخاصة باليوم",


// lab financial
"lab.financial.title":"حسابات المعمل",
"lab.financial.description":"الإيرادات , المديونيات و اتجاهات الدفع لهذا المعمل",

    // Radiology sidebar
    "radiology.menu.dashboard": "الرئيسية",
    "radiology.menu.reservations": "الحجوزات",
    "radiology.menu.rays": "الأشعة",
    "radiology.menu.ray_categories": "فئات الأشعة",
    "radiology.menu.users": "المستخدمون",
    "radiology.menu.patients": "المرضى",
    "radiology.menu.roles": "الأدوار",
    "radiology.menu.financial": "الحسابات",
    "radiology.menu.notifications": "الإشعارات",

    // Patient sidebar
    "patient.menu.appointments": "المواعيد",
    "patient.menu.profile": "الملف الشخصي",
    "patient.menu.prescriptions": "الروشتات",
    "patient.menu.analyses": "التحاليل",
    "patient.menu.rays": "الأشعة",
    "patient.menu.chronic": "الأمراض المزمنة",
    "patient.menu.glasses": "نظارة المسافة",
    "patient.menu.reviews": "التقييمات",
    "patient.menu.reels": "ريلز",
    "patient.menu.questionnaires": "الاستبيانات",
    "patient.menu.chat": "الدردشة",

	// Shared chat
	"shared.chat.title": "الدردشة",
	"shared.chat.description": "الدردشة الحقيقية مع المرضى والمستخدمين",
	"shared.chat.search": "بحث في الدردشات",
	"shared.chat.no_conversations": "لا يوجد دردشات بعد",
	"shared.chat.patients": "المرضى",
	"shared.chat.users": "المستخدمون",
	"shared.chat.message": "الرسالة",
	"shared.chat.type_message": "اكتب رسالتك...",
	"shared.chat.no_messages": "لا يوجد رسائل بعد",
	"shared.chat.insert": "أدخل",
	"shared.chat.toggle_emoji_picker": "تبديل منشئ الرموز",
	"shared.chat.send": "إرسال",
	"shared.chat.select_or_start_conversation": "اختر أو بدء الدردشة",

// notifications
"notifications.title": "الإشعارات",
"notifications.description": "الإشعارات المتاحة في العيادة",
"notifications.search": "بحث بالاسم أو المحتوى أو الحالة...",
"notifications.type": "النوع",
"notifications.priority": "الأولوية",
"notifications.module": "الموديل",
"notifications.unread": "غير مقروء",
"notifications.mark_read": "تحديث الإشعارات",
"notifications.mark_all_as_read": "تحديث الإشعارات",
"notifications.loading_notifications": "جاري تحميل الإشعارات...",
"notifications.failed_to_load_notifications": "فشل تحميل الإشعارات...",
"notifications.no_notifications_found": "لا يوجد إشعارات",
"notifications.previous": "السابق",
"notifications.next": "التالي",
"notifications.page": "الصفحة",
"notifications.of": "من",
"notifications.total": "الكل",
"notifications.active": "نشط",
"notifications.inactive": "غير نشط",
"notifications.delete_confirmation_description": "هذا الإجراء لا يمكن التراجع عنه.",
"notifications.delete_confirmation": "هذا الإجراء لا يمكن التراجع عنه.",
"notifications.deleting": "جاري الحذف...",
"notifications.delete": "حذف",
"notifications.cancel": "إلغاء",
"notifications.saving": "جاري الحفظ...",
"notifications.save": "حفظ",
"notifications.close": "إغلاق",
"notifications.actions": "الإجراءات",
"notifications.all_types": "جميع الأنواع",
"notifications.all_priorities": "جميع الأولويات",
"notifications.all_modules": "جميع الموديلات",
"notifications.showing_unread_only": "عرض الإشعارات الغير مقروءة",
"notifications.show_unread_only": "عرض الإشعارات الغير مقروءة",
"notifications.new_appointment": "مواعيد جديدة",
"notifications.pending_reservation": "حجوزات معلقة",
"notifications.cancelled_reservation": "حجوزات ملغية",
"notifications.payment_pending": "دفعات معلقة",
"notifications.service_completed": "خدمات مكتملة",
"notifications.announcement": "إعلانات",
"notifications.high": "عالي",
"notifications.medium": "متوسط",
"notifications.low": "منخفض",

// financial
"financial.title": "الحسابات",
"financial.description": "الإيرادات , المديونيات و اتجاهات الدفع لهذا العيادة",
"financial.period": "الفترة",
"financial.last_3_months": "الأخير 3 أشهر",
"financial.last_6_months": "الأخير 6 أشهر",
"financial.last_12_months": "الأخير 12 أشهر",
"financial.total_revenue": "الإيرادات الكلية",
"financial.total_due": "المديونيات الكلية",
"financial.paid_records": "الدفعات المدفوعة",
"financial.unpaid_records": "الدفعات الغير مدفوعة",
"financial.revenue_trend": "اتجاهات الإيرادات",
"financial.breakdown": "التفصيل",
"financial.paid": "مدفوع",
"financial.due": "مديون",
"financial.clinic": "العيادة",
"financial.laboratory": "المعمل",
"financial.radiology": "الأشعة",
"financial.loading_financial_data": "جاري تحميل البيانات المالية...",
"financial.failed_to_load_financial_data": "فشل تحميل البيانات المالية...",
"financial.no_financial_data_found": "لا يوجد بيانات مالية",
"financial.previous": "السابق",
"financial.next": "التالي",
"financial.page": "الصفحة",
"financial.of": "من",
"financial.total": "الكل",
"financial.active": "نشط",
"financial.inactive": "غير نشط",
"financial.last_3_months": "الأخير 3 أشهر",
"financial.last_6_months": "الأخير 6 أشهر",
"financial.last_12_months": "الأخير 12 أشهر",
"financial.total_revenue": "الإيرادات الكلية",
"financial.total_due": "المديونيات الكلية",
"financial.paid_records": "الدفعات المدفوعة",
"financial.unpaid_records": "الدفعات الغير مدفوعة",
"financial.revenue_trend": "اتجاهات الإيرادات",
"financial.breakdown": "التفصيل",
"financial.paid": "مدفوع",
"financial.due": "مديون",
"financial.clinic": "العيادة",
"financial.laboratory": "المعمل",
"financial.radiology": "الأشعة",

// auth
"auth.name_and_email_required": "الاسم والبريد الإلكتروني مطلوب",
"auth.profile_updated": "تم تحديث الملف الشخصي",
"auth.failed_to_update_profile": "فشل تحديث الملف الشخصي",
"auth.unknown_error": "خطأ غير معروف",
"auth.name": "الاسم",
"auth.email": "البريد الإلكتروني",
"auth.phone": "الهاتف",
"auth.job_title": "الوظيفة",
"auth.new_password": "كلمة المرور الجديدة",
"auth.confirm_new_password": "تأكيد كلمة المرور الجديدة",
"auth.current_password": "كلمة المرور الحالية",
	"auth.user_data": "بيانات المستخدم",
	"auth.update_profile": "تحديث الملف الشخصي",
	"auth.save": "حفظ",
	"auth.cancel": "إلغاء",
	"auth.close": "إغلاق",
	"auth.saving": "جاري الحفظ...",
	"auth.saving_profile": "جاري تحديث الملف الشخصي...",
	"auth.saving_profile_description": "جاري تحديث الملف الشخصي...",
  },
};

const LanguageContext = createContext<LanguageContextValue>({
  lang: "en",
  dir: "ltr",
  t: (key: string) => key,
  setLanguage: () => undefined,
  toggleLanguage: () => undefined,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    const stored = window.localStorage.getItem("lang");
    return stored === "ar" || stored === "en" ? stored : "en";
  });

  const dir: "ltr" | "rtl" = lang === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    if (typeof document !== "undefined") {
      document.documentElement.lang = lang;
      document.documentElement.dir = dir;
    }
    if (typeof window !== "undefined") {
      window.localStorage.setItem("lang", lang);
    }
  }, [lang, dir]);

  const t = (key: string) => {
    const table = translations[lang] || translations.en;
    return table[key] || key;
  };

  const setLanguage = (next: Language) => setLang(next);
  const toggleLanguage = () => setLang((prev) => (prev === "en" ? "ar" : "en"));

  return (
    <LanguageContext.Provider value={{ lang, dir, t, setLanguage, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

